import type { TourStep } from './tour-types';

export const VAD_TOUR_VERSION = '2026.09';

export const VAD_PRODUCT_TOUR: TourStep[] = [
  {
    id: 'home-overview',
    targetId: 'home-overview',
    route: '/home',
    title: 'Your starting point',
    body: 'This is your VAD home. It brings live markets, featured opportunities and community activity together in one place.',
  },
  {
    id: 'search-markets',
    targetId: 'global-search',
    route: '/home',
    title: 'Find a market quickly',
    body: 'Use Search whenever you already know the event, topic or market you want to find.',
  },
  {
    id: 'explore-markets',
    targetId: 'home-explore-markets',
    route: '/home',
    title: 'Browse every market',
    body: 'Tap Explore markets when you want to see the full market catalogue and compare more choices.',
  },
  {
    id: 'featured-markets',
    targetId: 'home-featured-markets',
    route: '/home',
    title: 'See what deserves a closer look',
    body: 'Featured markets highlight questions that are currently important or useful to discover.',
  },
  {
    id: 'market-categories',
    targetId: 'home-categories',
    route: '/home',
    title: 'Jump into a topic',
    body: 'These shortcuts take you straight to markets in a category without making you search first.',
  },
  {
    id: 'trending-markets',
    targetId: 'home-trending',
    route: '/home',
    title: 'Follow current activity',
    body: 'Trending markets help you notice questions where people have been active recently.',
  },
  {
    id: 'community-preview',
    targetId: 'home-community',
    route: '/home',
    title: 'Learn from the community',
    body: 'Read what other people are saying, then open the full feed when you want more context around a market.',
  },
  {
    id: 'market-discovery',
    targetId: 'markets-discovery',
    route: '/markets',
    title: 'Narrow down the market list',
    body: 'Search, choose a category and change the ordering here. Use these controls together to get to the right market faster.',
  },
  {
    id: 'market-cards',
    targetId: 'markets-results',
    route: '/markets',
    title: 'Open a market before taking a position',
    body: 'Each market card shows the question and current pricing. Open one to review the full details before you decide what to do.',
  },
  {
    id: 'wallet-balance',
    targetId: 'wallet-balance',
    route: '/wallet',
    title: 'Know what is available',
    body: 'Your wallet separates money that is ready to use, money committed to open orders and withdrawals that are still processing.',
  },
  {
    id: 'wallet-actions',
    targetId: 'wallet-actions',
    route: '/wallet',
    title: 'Move money from one place',
    body: 'Deposit, withdraw and open your payment history from these shortcuts. VAD keeps each currency balance separate.',
  },
  {
    id: 'wallet-activity',
    targetId: 'wallet-activity',
    route: '/wallet',
    title: 'Check what happened to a payment',
    body: 'Recent activity shows the latest deposits, withdrawals and refunds. Open an item when you need its full status.',
  },
  {
    id: 'portfolio-summary',
    targetId: 'portfolio-summary',
    route: '/portfolio',
    title: 'See what you currently hold',
    body: 'Your portfolio brings together your positions, shares held, open orders and the currencies you are using.',
  },
  {
    id: 'portfolio-switcher',
    targetId: 'portfolio-switcher',
    route: '/portfolio',
    title: 'Switch between holdings and orders',
    body: 'Use these tabs to move between positions you already hold and orders that are still waiting to fill.',
  },
  {
    id: 'verification',
    targetId: 'account-verification',
    route: '/account',
    title: 'Check your verification',
    body: 'Identity verification lives here. VAD will show your current status and the next step when verification is required.',
  },
  {
    id: 'funding-settings',
    targetId: 'account-funding',
    route: '/account',
    title: 'Review funding access',
    body: 'Open Funding & withdrawals to see availability, limits, fees and payment activity connected to your account.',
  },
  {
    id: 'tour-and-policies',
    targetId: 'account-guidance',
    route: '/account',
    title: 'Come back whenever you need help',
    body: 'You can take this guided tour again from your account settings, and you can always return to VAD policies and privacy information here.',
  },
];
