-- VAD Phase 35: provider-neutral oracle runtime foundation.
-- External API calls and secrets stay in Edge Functions. PostgreSQL remains the
-- authority for provider governance, observation integrity, consensus and settlement state.

create table if not exists oracle.provider_resources (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references integration.providers(id) on delete cascade,
  resource_type text not null check (resource_type in ('CRYPTO_PAIR','CANONICAL_EVENT','SPORTS_COMPETITION','PUBLIC_EVENT')),
  canonical_key text not null check (char_length(trim(canonical_key)) between 1 and 180),
  external_key text not null check (char_length(trim(external_key)) between 1 and 300),
  status text not null default 'ACTIVE' check (status in ('ACTIVE','DISABLED')),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata)='object'),
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  unique(provider_id,resource_type,canonical_key)
);

create index if not exists oracle_provider_resources_lookup_idx
  on oracle.provider_resources(resource_type,canonical_key,status,provider_id);

do $$
begin
  if not exists (
    select 1 from pg_trigger
    where tgname='oracle_provider_resources_updated_at'
      and tgrelid='oracle.provider_resources'::regclass
  ) then
    create trigger oracle_provider_resources_updated_at
      before update on oracle.provider_resources
      for each row execute function private.set_updated_at();
  end if;
end $$;

alter table oracle.provider_resources enable row level security;
revoke all on oracle.provider_resources from public,anon,authenticated;
grant select,insert,update,delete on oracle.provider_resources to service_role;

create table if not exists oracle.ingestion_attempts (
  id bigint generated by default as identity primary key,
  event_id bigint references market.canonical_events(id) on delete cascade,
  provider_id bigint not null references integration.providers(id) on delete cascade,
  resolver_type text not null,
  attempt_key text not null unique,
  status text not null check (status in ('SUCCEEDED','FAILED','SKIPPED')),
  request_metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(request_metadata)='object'),
  response_metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(response_metadata)='object'),
  failure_code text,
  latency_ms integer check (latency_ms is null or latency_ms>=0),
  started_at timestamptz not null,
  completed_at timestamptz not null default statement_timestamp(),
  created_at timestamptz not null default statement_timestamp()
);

create index if not exists oracle_ingestion_attempts_event_created_idx
  on oracle.ingestion_attempts(event_id,created_at desc);
create index if not exists oracle_ingestion_attempts_provider_created_idx
  on oracle.ingestion_attempts(provider_id,created_at desc);

alter table oracle.ingestion_attempts enable row level security;
revoke all on oracle.ingestion_attempts from public,anon,authenticated;
grant select,insert,update on oracle.ingestion_attempts to service_role;

-- Register the first provider adapters without activating them. Provider activation
-- remains subject to the existing maker/checker provider governance flow.
insert into integration.providers as p(
  code,name,provider_type,environment,status,priority,capabilities,public_metadata,secret_reference
)
values
  (
    'PYTH','Pyth Network','ORACLE','PRODUCTION','DISABLED',10,
    '["CRYPTO_PRICE_TIMESTAMP","CRYPTO_PRICE_THRESHOLD"]'::jsonb,
    '{"configured":false,"adapter":"PYTH_HERMES_V2","base_url":"https://hermes.pyth.network","credential_mode":"BEARER_SECRET","settlement_role":"PRIMARY_OR_CORROBORATING"}'::jsonb,
    'PYTH_API_KEY'
  ),
  (
    'COINGECKO','CoinGecko','ORACLE','PRODUCTION','DISABLED',20,
    '["CRYPTO_PRICE_HISTORY","CRYPTO_PRICE_THRESHOLD"]'::jsonb,
    '{"configured":false,"adapter":"COINGECKO_DEMO_V3","base_url":"https://api.coingecko.com/api/v3","credential_mode":"X_CG_DEMO_API_KEY","settlement_role":"CORROBORATING"}'::jsonb,
    'COINGECKO_API_KEY'
  ),
  (
    'FOOTBALL_DATA','Football-Data.org','ORACLE','PRODUCTION','DISABLED',30,
    '["FOOTBALL_MATCH_RESULT"]'::jsonb,
    '{"configured":false,"adapter":"FOOTBALL_DATA_V4","base_url":"https://api.football-data.org/v4","credential_mode":"X_AUTH_TOKEN","settlement_role":"OBJECTIVE_EVENT_SOURCE","attribution_required":true}'::jsonb,
    'FOOTBALL_DATA_API_KEY'
  ),
  (
    'DIA','DIA','ORACLE','PRODUCTION','DISABLED',40,
    '["CRYPTO_REFERENCE_PRICE","CRYPTO_PRICE_LATEST"]'::jsonb,
    '{"configured":true,"adapter":"DIA_REST_V1","base_url":"https://api.diadata.org","credential_mode":"NONE","settlement_role":"REFERENCE_ONLY"}'::jsonb,
    null
  )
on conflict(code,environment) do update set
  name=excluded.name,
  provider_type=excluded.provider_type,
  priority=excluded.priority,
  capabilities=excluded.capabilities,
  secret_reference=excluded.secret_reference,
  public_metadata=p.public_metadata || (excluded.public_metadata - 'configured'),
  updated_at=statement_timestamp();

-- Canonical resource mappings are backend-owned. AI may suggest a subject, but it
-- never gets to invent provider identifiers used for financial resolution.
insert into oracle.provider_resources(provider_id,resource_type,canonical_key,external_key,status,metadata)
select p.id,'CRYPTO_PAIR',v.canonical_key,v.external_key,'ACTIVE',v.metadata
from integration.providers p
join (values
  ('PYTH','BTC/USD','Crypto.BTC/USD','{"quote":"USD","settlement_eligible":true,"discovery":"EXACT_SYMBOL","max_timestamp_delta_seconds":120}'::jsonb),
  ('PYTH','ETH/USD','Crypto.ETH/USD','{"quote":"USD","settlement_eligible":true,"discovery":"EXACT_SYMBOL","max_timestamp_delta_seconds":120}'::jsonb),
  ('PYTH','USDC/USD','Crypto.USDC/USD','{"quote":"USD","settlement_eligible":true,"discovery":"EXACT_SYMBOL","max_timestamp_delta_seconds":120}'::jsonb),
  ('COINGECKO','BTC/USD','bitcoin','{"quote":"USD","settlement_eligible":true,"historical_mode":"RANGE_NEAREST","max_timestamp_delta_seconds":600}'::jsonb),
  ('COINGECKO','ETH/USD','ethereum','{"quote":"USD","settlement_eligible":true,"historical_mode":"RANGE_NEAREST","max_timestamp_delta_seconds":600}'::jsonb),
  ('COINGECKO','USDC/USD','usd-coin','{"quote":"USD","settlement_eligible":true,"historical_mode":"RANGE_NEAREST","max_timestamp_delta_seconds":600}'::jsonb),
  ('DIA','BTC/USD','BTC','{"quote":"USD","settlement_eligible":false,"reference_only":true,"max_timestamp_delta_seconds":180}'::jsonb),
  ('DIA','ETH/USD','ETH','{"quote":"USD","settlement_eligible":false,"reference_only":true,"max_timestamp_delta_seconds":180}'::jsonb),
  ('DIA','USDC/USD','USDC','{"quote":"USD","settlement_eligible":false,"reference_only":true,"max_timestamp_delta_seconds":180}'::jsonb)
) as v(provider_code,canonical_key,external_key,metadata)
  on p.code=v.provider_code and p.environment='PRODUCTION'
on conflict(provider_id,resource_type,canonical_key) do update set
  external_key=excluded.external_key,
  status=excluded.status,
  metadata=excluded.metadata,
  updated_at=statement_timestamp();

create or replace function public.admin_oracle_runtime_access()
returns jsonb
language sql
stable
security definer
set search_path=''
as $$
  select jsonb_build_object(
    'canRead', private.has_permission('oracle.review') or private.has_permission('providers.manage'),
    'canProcess', private.has_permission('oracle.review'),
    'canManageProviders', private.has_permission('providers.manage')
  );
$$;
revoke all on function public.admin_oracle_runtime_access() from public,anon;
grant execute on function public.admin_oracle_runtime_access() to authenticated;

create or replace function public.admin_oracle_provider_resources()
returns table(
  provider_code text,
  environment text,
  provider_status text,
  resource_type text,
  canonical_key text,
  external_key text,
  resource_status text,
  metadata jsonb,
  updated_at timestamptz
)
language plpgsql
stable
security definer
set search_path=''
as $$
begin
  if not private.has_permission('oracle.review') and not private.has_permission('providers.manage') then
    raise exception 'Permission required' using errcode='42501';
  end if;
  return query
  select p.code,p.environment,p.status,r.resource_type,r.canonical_key,r.external_key,r.status,r.metadata,r.updated_at
  from oracle.provider_resources r
  join integration.providers p on p.id=r.provider_id
  where p.provider_type='ORACLE'
  order by p.priority,p.code,r.resource_type,r.canonical_key;
end;
$$;
revoke all on function public.admin_oracle_provider_resources() from public,anon;
grant execute on function public.admin_oracle_provider_resources() to authenticated;

create or replace function public.admin_upsert_oracle_provider_resource(
  p_provider_code text,
  p_environment text,
  p_resource_type text,
  p_canonical_key text,
  p_external_key text,
  p_status text default 'ACTIVE',
  p_metadata jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path=''
as $$
declare
  provider_id bigint;
  resource_id bigint;
  resource_type text:=upper(trim(p_resource_type));
  resource_status text:=upper(trim(p_status));
begin
  if not private.has_permission('providers.manage') then
    raise exception 'Permission required' using errcode='42501';
  end if;
  if resource_type not in ('CRYPTO_PAIR','CANONICAL_EVENT','SPORTS_COMPETITION','PUBLIC_EVENT') then
    raise exception 'Invalid oracle resource type' using errcode='22023';
  end if;
  if resource_status not in ('ACTIVE','DISABLED') then
    raise exception 'Invalid oracle resource status' using errcode='22023';
  end if;
  if jsonb_typeof(coalesce(p_metadata,'{}'::jsonb))<>'object' then
    raise exception 'Resource metadata must be an object' using errcode='22023';
  end if;
  select id into provider_id
  from integration.providers
  where code=upper(trim(p_provider_code))
    and environment=upper(trim(p_environment))
    and provider_type='ORACLE';
  if provider_id is null then
    raise exception 'Oracle provider not found' using errcode='P0002';
  end if;
  insert into oracle.provider_resources(provider_id,resource_type,canonical_key,external_key,status,metadata)
  values(provider_id,resource_type,trim(p_canonical_key),trim(p_external_key),resource_status,coalesce(p_metadata,'{}'::jsonb))
  on conflict(provider_id,resource_type,canonical_key) do update set
    external_key=excluded.external_key,
    status=excluded.status,
    metadata=excluded.metadata,
    updated_at=statement_timestamp()
  returning id into resource_id;
  return resource_id;
end;
$$;
revoke all on function public.admin_upsert_oracle_provider_resource(text,text,text,text,text,text,jsonb) from public,anon;
grant execute on function public.admin_upsert_oracle_provider_resource(text,text,text,text,text,text,jsonb) to authenticated;

create or replace function public.admin_bind_oracle_event_resource(
  p_event_public_id uuid,
  p_provider_code text,
  p_environment text,
  p_external_key text,
  p_metadata jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path=''
as $$
declare
  provider_id bigint;
  event_id bigint;
  resource_id bigint;
begin
  if not private.has_permission('oracle.review') and not private.has_permission('providers.manage') then
    raise exception 'Permission required' using errcode='42501';
  end if;
  if jsonb_typeof(coalesce(p_metadata,'{}'::jsonb))<>'object' then
    raise exception 'Resource metadata must be an object' using errcode='22023';
  end if;
  select id into event_id from market.canonical_events where public_id=p_event_public_id;
  if event_id is null then raise exception 'Event not found' using errcode='P0002'; end if;
  select id into provider_id
  from integration.providers
  where code=upper(trim(p_provider_code))
    and environment=upper(trim(p_environment))
    and provider_type='ORACLE';
  if provider_id is null then raise exception 'Oracle provider not found' using errcode='P0002'; end if;
  insert into oracle.provider_resources(provider_id,resource_type,canonical_key,external_key,status,metadata)
  values(
    provider_id,'CANONICAL_EVENT',p_event_public_id::text,trim(p_external_key),'ACTIVE',
    coalesce(p_metadata,'{}'::jsonb) || jsonb_build_object('bound_at',statement_timestamp(),'bound_by',auth.uid())
  )
  on conflict(provider_id,resource_type,canonical_key) do update set
    external_key=excluded.external_key,
    status='ACTIVE',
    metadata=excluded.metadata,
    updated_at=statement_timestamp()
  returning id into resource_id;
  return resource_id;
end;
$$;
revoke all on function public.admin_bind_oracle_event_resource(uuid,text,text,text,jsonb) from public,anon;
grant execute on function public.admin_bind_oracle_event_resource(uuid,text,text,text,jsonb) to authenticated;

create or replace function public.internal_oracle_provider_catalog()
returns jsonb
language plpgsql
stable
security definer
set search_path=''
as $$
declare result jsonb;
begin
  if auth.role()<>'service_role' then raise exception 'Service role required' using errcode='42501'; end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',p.id,
    'code',p.code,
    'name',p.name,
    'environment',p.environment,
    'status',p.status,
    'priority',p.priority,
    'capabilities',p.capabilities,
    'configured',coalesce((p.public_metadata->>'configured')::boolean,false),
    'adapter',p.public_metadata->>'adapter',
    'baseUrl',p.public_metadata->>'base_url',
    'secretReference',p.secret_reference,
    'publicMetadata',p.public_metadata,
    'resources',coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',r.id,
        'resourceType',r.resource_type,
        'canonicalKey',r.canonical_key,
        'externalKey',r.external_key,
        'status',r.status,
        'metadata',r.metadata
      ) order by r.resource_type,r.canonical_key)
      from oracle.provider_resources r
      where r.provider_id=p.id
    ),'[]'::jsonb)
  ) order by p.priority,p.code),'[]'::jsonb) into result
  from integration.providers p
  where p.provider_type='ORACLE';
  return result;
end;
$$;
revoke all on function public.internal_oracle_provider_catalog() from public,anon,authenticated;
grant execute on function public.internal_oracle_provider_catalog() to service_role;

create or replace function public.internal_oracle_due_events(
  p_event_public_id uuid default null,
  p_limit integer default 20
)
returns jsonb
language plpgsql
stable
security definer
set search_path=''
as $$
declare result jsonb;
begin
  if auth.role()<>'service_role' then raise exception 'Service role required' using errcode='42501'; end if;
  with due as (
    select e.id,e.public_id,e.title,e.category,e.status,e.normalized_parameters,e.resolution_scope,
           e.closes_at,e.resolves_after,
           op.id oracle_policy_id,op.public_id oracle_policy_public_id,op.source_hierarchy,op.consensus_rule,
           oc.code capability_code
    from market.canonical_events e
    join oracle.event_policy_bindings b on b.event_id=e.id
    join oracle.policies op on op.id=b.oracle_policy_id and op.status='ACTIVE'
    join oracle.capabilities oc on oc.id=op.capability_id
    where e.status in ('AWAITING_ORACLE','PROVISIONALLY_RESOLVED')
      and coalesce(e.resolves_after,e.closes_at)<=statement_timestamp()
      and (p_event_public_id is null or e.public_id=p_event_public_id)
      and not exists(
        select 1 from oracle.disputes d
        where d.event_id=e.id and d.status in ('OPEN','UNDER_REVIEW','ESCALATED')
      )
    order by coalesce(e.resolves_after,e.closes_at),e.id
    limit greatest(1,least(coalesce(p_limit,20),100))
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'eventId',d.id,
    'eventPublicId',d.public_id,
    'title',d.title,
    'category',d.category,
    'status',d.status,
    'normalizedParameters',d.normalized_parameters,
    'resolutionScope',d.resolution_scope,
    'closesAt',d.closes_at,
    'resolvesAfter',d.resolves_after,
    'oraclePolicyId',d.oracle_policy_id,
    'oraclePolicyPublicId',d.oracle_policy_public_id,
    'capabilityCode',d.capability_code,
    'sourceHierarchy',d.source_hierarchy,
    'consensusRule',d.consensus_rule,
    'outcomes',coalesce((
      select jsonb_agg(jsonb_build_object('code',o.code,'label',o.label) order by i.id,o.display_order)
      from market.instruments i
      join market.outcomes o on o.instrument_id=i.id
      where i.canonical_event_id=d.id
    ),'[]'::jsonb)
  ) order by coalesce(d.resolves_after,d.closes_at),d.id),'[]'::jsonb) into result
  from due d;
  return result;
end;
$$;
revoke all on function public.internal_oracle_due_events(uuid,integer) from public,anon,authenticated;
grant execute on function public.internal_oracle_due_events(uuid,integer) to service_role;

create or replace function public.internal_record_oracle_provider_health(
  p_provider_code text,
  p_environment text,
  p_health_status text,
  p_configured boolean,
  p_latency_ms integer default null,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare provider_id bigint; health_status text:=upper(trim(p_health_status));
begin
  if auth.role()<>'service_role' then raise exception 'Service role required' using errcode='42501'; end if;
  if health_status not in ('HEALTHY','DEGRADED','UNAVAILABLE','UNKNOWN') then
    raise exception 'Invalid provider health status' using errcode='22023';
  end if;
  if jsonb_typeof(coalesce(p_metadata,'{}'::jsonb))<>'object' then
    raise exception 'Provider health metadata must be an object' using errcode='22023';
  end if;
  select id into provider_id from integration.providers
  where code=upper(trim(p_provider_code)) and environment=upper(trim(p_environment)) and provider_type='ORACLE';
  if provider_id is null then raise exception 'Oracle provider not found' using errcode='P0002'; end if;
  update integration.providers
     set public_metadata=jsonb_set(coalesce(public_metadata,'{}'::jsonb),'{configured}',to_jsonb(coalesce(p_configured,false)),true),
         updated_at=statement_timestamp()
   where id=provider_id;
  insert into integration.provider_health(provider_id,status,latency_ms,success_rate,error_rate,last_success_at,last_failure_at,checked_at,metadata)
  values(
    provider_id,health_status,p_latency_ms,
    case when health_status='HEALTHY' then 1 else 0 end,
    case when health_status='HEALTHY' then 0 else 1 end,
    case when health_status='HEALTHY' then statement_timestamp() else null end,
    case when health_status in ('DEGRADED','UNAVAILABLE') then statement_timestamp() else null end,
    statement_timestamp(),coalesce(p_metadata,'{}'::jsonb)
  )
  on conflict(provider_id) do update set
    status=excluded.status,
    latency_ms=excluded.latency_ms,
    success_rate=excluded.success_rate,
    error_rate=excluded.error_rate,
    last_success_at=case when excluded.status='HEALTHY' then excluded.checked_at else integration.provider_health.last_success_at end,
    last_failure_at=case when excluded.status in ('DEGRADED','UNAVAILABLE') then excluded.checked_at else integration.provider_health.last_failure_at end,
    checked_at=excluded.checked_at,
    metadata=excluded.metadata;
end;
$$;
revoke all on function public.internal_record_oracle_provider_health(text,text,text,boolean,integer,jsonb) from public,anon,authenticated;
grant execute on function public.internal_record_oracle_provider_health(text,text,text,boolean,integer,jsonb) to service_role;

create or replace function public.internal_record_oracle_attempt(
  p_event_id bigint,
  p_provider_code text,
  p_environment text,
  p_resolver_type text,
  p_attempt_key text,
  p_status text,
  p_request_metadata jsonb,
  p_response_metadata jsonb,
  p_failure_code text,
  p_latency_ms integer,
  p_started_at timestamptz
)
returns bigint
language plpgsql
security definer
set search_path=''
as $$
declare provider_id bigint; attempt_id bigint; attempt_status text:=upper(trim(p_status));
begin
  if auth.role()<>'service_role' then raise exception 'Service role required' using errcode='42501'; end if;
  if attempt_status not in ('SUCCEEDED','FAILED','SKIPPED') then raise exception 'Invalid attempt status' using errcode='22023'; end if;
  select id into provider_id from integration.providers
  where code=upper(trim(p_provider_code)) and environment=upper(trim(p_environment)) and provider_type='ORACLE';
  if provider_id is null then raise exception 'Oracle provider not found' using errcode='P0002'; end if;
  insert into oracle.ingestion_attempts(
    event_id,provider_id,resolver_type,attempt_key,status,request_metadata,response_metadata,failure_code,latency_ms,started_at,completed_at
  ) values(
    p_event_id,provider_id,upper(trim(p_resolver_type)),p_attempt_key,attempt_status,
    coalesce(p_request_metadata,'{}'::jsonb),coalesce(p_response_metadata,'{}'::jsonb),
    nullif(trim(coalesce(p_failure_code,'')),''),p_latency_ms,coalesce(p_started_at,statement_timestamp()),statement_timestamp()
  )
  on conflict(attempt_key) do update set
    status=excluded.status,
    response_metadata=excluded.response_metadata,
    failure_code=excluded.failure_code,
    latency_ms=excluded.latency_ms,
    completed_at=statement_timestamp()
  returning id into attempt_id;
  return attempt_id;
end;
$$;
revoke all on function public.internal_record_oracle_attempt(bigint,text,text,text,text,text,jsonb,jsonb,text,integer,timestamptz) from public,anon,authenticated;
grant execute on function public.internal_record_oracle_attempt(bigint,text,text,text,text,text,jsonb,jsonb,text,integer,timestamptz) to service_role;

-- Observation integrity hardening: a provider is one independent vote. The caller
-- cannot manufacture multiple source_code values for the same provider.
create or replace function oracle.record_verified_observation(
  p_event_id bigint,
  p_provider_id bigint,
  p_source_code text,
  p_observed_outcome text,
  p_payload jsonb,
  p_evidence_reference text,
  p_observed_at timestamptz,
  p_idempotency_key text
)
returns bigint
language plpgsql
security definer
set search_path=''
as $$
declare
  provider integration.providers;
  ev market.canonical_events;
  observation_id bigint;
begin
  if auth.role()<>'service_role' then raise exception 'Service role required' using errcode='42501'; end if;
  if p_idempotency_key is null or char_length(p_idempotency_key)<8 then
    raise exception 'Valid observation idempotency key required' using errcode='22023';
  end if;
  if jsonb_typeof(coalesce(p_payload,'{}'::jsonb))<>'object' then
    raise exception 'Observation payload must be an object' using errcode='22023';
  end if;
  select * into provider from integration.providers where id=p_provider_id;
  if provider.id is null or provider.provider_type<>'ORACLE' or provider.status not in ('ACTIVE','DEGRADED') then
    raise exception 'Eligible oracle provider required' using errcode='23514';
  end if;
  if upper(trim(coalesce(p_source_code,'')))<>provider.code then
    raise exception 'Oracle source code must match provider identity' using errcode='23514';
  end if;
  select * into ev from market.canonical_events where id=p_event_id;
  if ev.id is null then raise exception 'Event not found' using errcode='P0002'; end if;
  if ev.status not in ('AWAITING_ORACLE','PROVISIONALLY_RESOLVED','DISPUTED') then
    raise exception 'Event is not accepting oracle observations' using errcode='P0001';
  end if;
  if not exists(
    select 1 from market.instruments i
    join market.outcomes o on o.instrument_id=i.id
    where i.canonical_event_id=ev.id and o.code=upper(trim(p_observed_outcome))
  ) then
    raise exception 'Observed outcome is invalid for event' using errcode='22023';
  end if;
  if coalesce(p_observed_at,statement_timestamp())>statement_timestamp()+interval '5 minutes' then
    raise exception 'Observation timestamp is unreasonably in the future' using errcode='22023';
  end if;
  insert into oracle.observations(
    event_id,provider_id,source_code,observed_outcome,observation_payload,evidence_reference,observed_at,verification_status,idempotency_key
  ) values(
    ev.id,provider.id,provider.code,upper(trim(p_observed_outcome)),coalesce(p_payload,'{}'::jsonb),p_evidence_reference,
    coalesce(p_observed_at,statement_timestamp()),'VERIFIED',p_idempotency_key
  )
  on conflict(idempotency_key) do nothing
  returning id into observation_id;
  if observation_id is null then
    select id into observation_id from oracle.observations where idempotency_key=p_idempotency_key;
  end if;
  perform oracle.evaluate_event_consensus(ev.id);
  return observation_id;
end;
$$;
revoke all on function oracle.record_verified_observation(bigint,bigint,text,text,jsonb,text,timestamptz,text) from public,anon,authenticated;
grant execute on function oracle.record_verified_observation(bigint,bigint,text,text,jsonb,text,timestamptz,text) to service_role;

-- Consensus V2 counts the latest verified observation from each eligible provider,
-- never arbitrary source labels. This closes the multi-source spoofing path in V1.
create or replace function oracle.evaluate_event_consensus(p_event_id bigint)
returns bigint
language plpgsql
security definer
set search_path=''
as $$
declare
  ev market.canonical_events;
  binding oracle.event_policy_bindings;
  pol oracle.policies;
  quorum integer;
  winning_code text;
  winning_count integer;
  runner_up_count integer;
  resolution_id bigint;
  previous_code text;
  evidence jsonb;
begin
  select * into ev from market.canonical_events where id=p_event_id for update;
  if ev.id is null then raise exception 'Event not found' using errcode='P0002'; end if;
  if ev.status not in ('AWAITING_ORACLE','PROVISIONALLY_RESOLVED','DISPUTED') then return null; end if;
  if exists(
    select 1 from oracle.disputes d
    where d.event_id=ev.id and d.status in ('OPEN','UNDER_REVIEW','ESCALATED')
  ) then
    return (select id from oracle.resolutions where event_id=ev.id and status='PROVISIONAL' limit 1);
  end if;
  select * into binding from oracle.event_policy_bindings where event_id=ev.id;
  select * into pol from oracle.policies where id=binding.oracle_policy_id;
  if pol.id is null or pol.status<>'ACTIVE' then
    raise exception 'Active oracle policy required' using errcode='23514';
  end if;
  quorum:=coalesce(
    (pol.consensus_rule->>'min_agreeing_providers')::integer,
    (pol.consensus_rule->>'min_agreeing_sources')::integer,
    (pol.consensus_rule->>'quorum')::integer,
    2
  );
  if quorum<1 then raise exception 'Oracle consensus quorum must be at least one' using errcode='23514'; end if;

  with latest as (
    select ranked.*
    from (
      select o.*,p.code as provider_code,
             row_number() over(partition by o.provider_id order by o.observed_at desc,o.received_at desc,o.id desc) as rn
      from oracle.observations o
      join integration.providers p on p.id=o.provider_id
      where o.event_id=ev.id
        and o.verification_status='VERIFIED'
        and p.provider_type='ORACLE'
        and p.status in ('ACTIVE','DEGRADED')
    ) ranked
    where ranked.rn=1
  ), counts as (
    select observed_outcome,count(*)::integer provider_count
    from latest
    group by observed_outcome
  ), ranked_counts as (
    select observed_outcome,provider_count,
           row_number() over(order by provider_count desc,observed_outcome) rn
    from counts
  )
  select max(observed_outcome) filter(where rn=1),
         coalesce(max(provider_count) filter(where rn=1),0),
         coalesce(max(provider_count) filter(where rn=2),0)
    into winning_code,winning_count,runner_up_count
  from ranked_counts;

  if winning_code is null or winning_count<quorum or winning_count=runner_up_count then return null; end if;

  with latest as (
    select ranked.*
    from (
      select o.*,p.code as provider_code,
             row_number() over(partition by o.provider_id order by o.observed_at desc,o.received_at desc,o.id desc) as rn
      from oracle.observations o
      join integration.providers p on p.id=o.provider_id
      where o.event_id=ev.id
        and o.verification_status='VERIFIED'
        and p.provider_type='ORACLE'
        and p.status in ('ACTIVE','DEGRADED')
    ) ranked
    where ranked.rn=1
  )
  select jsonb_build_object(
    'algorithm','PROVIDER_QUORUM_V2',
    'policy_id',pol.public_id,
    'required_providers',quorum,
    'winning_provider_count',winning_count,
    'observations',coalesce(jsonb_agg(jsonb_build_object(
      'source_code',o.provider_code,
      'provider_id',o.provider_id,
      'outcome',o.observed_outcome,
      'observed_at',o.observed_at,
      'evidence_reference',o.evidence_reference
    ) order by o.received_at),'[]'::jsonb)
  ) into evidence
  from latest o;

  select id,outcome_code into resolution_id,previous_code
  from oracle.resolutions where event_id=ev.id and status='PROVISIONAL' for update;
  if resolution_id is null then
    insert into oracle.resolutions(event_id,oracle_policy_id,outcome_code,status,consensus_evidence,created_by)
    values(ev.id,pol.id,winning_code,'PROVISIONAL',coalesce(evidence,'{}'::jsonb),null)
    returning id into resolution_id;
  elsif previous_code is distinct from winning_code then
    update oracle.resolutions
       set outcome_code=winning_code,consensus_evidence=coalesce(evidence,'{}'::jsonb),created_at=statement_timestamp()
     where id=resolution_id;
  else
    update oracle.resolutions set consensus_evidence=coalesce(evidence,'{}'::jsonb) where id=resolution_id;
  end if;
  update market.canonical_events
     set status='PROVISIONALLY_RESOLVED',updated_at=statement_timestamp()
   where id=ev.id;
  insert into eventing.domain_events(event_type,aggregate_type,aggregate_id,payload,idempotency_key)
  values(
    'ORACLE_CONSENSUS_REACHED','CANONICAL_EVENT',ev.public_id::text,
    jsonb_build_object('resolution_id',resolution_id,'outcome_code',winning_code,'provider_count',winning_count,'quorum',quorum,'algorithm','PROVIDER_QUORUM_V2'),
    'oracle-consensus-v2:'||ev.public_id::text||':'||winning_code||':'||winning_count::text
  )
  on conflict(idempotency_key) do nothing;
  return resolution_id;
end;
$$;
revoke all on function oracle.evaluate_event_consensus(bigint) from public,anon,authenticated;
grant execute on function oracle.evaluate_event_consensus(bigint) to service_role;

comment on table oracle.provider_resources is 'Backend-owned mapping from canonical VAD subjects/events to provider identifiers. AI must not write settlement identifiers directly.';
comment on table oracle.ingestion_attempts is 'Auditable external oracle fetch attempts. Secret values and credential-bearing URLs must never be stored here.';
