create table if not exists compliance.kyc_access_overrides (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  scope text not null default 'SANDBOX' check (scope in ('SANDBOX','ALL')),
  enabled boolean not null default true,
  reason text not null,
  expires_at timestamptz,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  unique(user_id)
);

create index if not exists kyc_access_overrides_active_idx
  on compliance.kyc_access_overrides(user_id,enabled,expires_at);

alter table compliance.kyc_access_overrides enable row level security;
revoke all on compliance.kyc_access_overrides from anon, authenticated;

create or replace function private.kyc_access_satisfies(
  p_user_id uuid,
  p_required_level text,
  p_environment text default 'PRODUCTION'
) returns boolean
language plpgsql
stable
security definer
set search_path=''
as $$
declare
  v_scope text;
begin
  if private.kyc_satisfies(p_user_id,p_required_level) then
    return true;
  end if;

  select o.scope into v_scope
  from compliance.kyc_access_overrides o
  where o.user_id=p_user_id
    and o.enabled
    and (o.expires_at is null or o.expires_at>statement_timestamp())
  limit 1;

  if v_scope='ALL' then return true; end if;
  return v_scope='SANDBOX' and upper(coalesce(p_environment,''))='SANDBOX';
end;
$$;

revoke all on function private.kyc_access_satisfies(uuid,text,text) from public,anon,authenticated;

create or replace function public.admin_kyc_access_overrides(
  p_search text default null,
  p_limit integer default 100
) returns table(
  user_id uuid,
  email text,
  display_name text,
  country_code text,
  provider_kyc_status text,
  verification_level text,
  provider_code text,
  override_enabled boolean,
  override_scope text,
  override_reason text,
  override_expires_at timestamptz,
  override_updated_at timestamptz
)
language plpgsql
stable
security definer
set search_path=''
as $$
begin
  if auth.uid() is null or not (
    private.is_super_admin()
    or private.has_permission('compliance.manage')
    or private.has_permission('users.manage')
  ) then
    raise exception 'Compliance or user management permission required' using errcode='42501';
  end if;

  return query
  with latest_kyc as (
    select distinct on (k.user_id)
      k.user_id,k.status,k.verification_level,p.code as provider_code
    from compliance.kyc_cases k
    left join integration.providers p on p.id=k.provider_id
    order by k.user_id,k.created_at desc,k.id desc
  )
  select
    a.id,
    a.email::text,
    coalesce(nullif(pr.display_name,''),nullif(pr.handle,''),split_part(coalesce(a.email,''),'@',1))::text,
    ua.country_code,
    coalesce(k.status,'NOT_STARTED')::text,
    coalesce(k.verification_level,'NONE')::text,
    k.provider_code::text,
    coalesce(o.enabled,false),
    o.scope::text,
    o.reason::text,
    o.expires_at,
    o.updated_at
  from auth.users a
  left join public.user_accounts ua on ua.user_id=a.id
  left join public.profiles pr on pr.user_id=a.id
  left join latest_kyc k on k.user_id=a.id
  left join compliance.kyc_access_overrides o on o.user_id=a.id
  where nullif(btrim(coalesce(p_search,'')),'') is null
     or lower(coalesce(a.email,'')) like '%'||lower(btrim(p_search))||'%'
     or lower(coalesce(pr.display_name,'')) like '%'||lower(btrim(p_search))||'%'
     or lower(coalesce(pr.handle,'')) like '%'||lower(btrim(p_search))||'%'
  order by coalesce(o.updated_at,a.created_at) desc
  limit greatest(1,least(coalesce(p_limit,100),250));
end;
$$;

grant execute on function public.admin_kyc_access_overrides(text,integer) to authenticated;

create or replace function public.admin_set_kyc_access_override(
  p_user_id uuid,
  p_scope text,
  p_enabled boolean,
  p_reason text,
  p_expires_at timestamptz default null
) returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_scope text:=upper(btrim(coalesce(p_scope,'')));
  v_reason text:=btrim(coalesce(p_reason,''));
begin
  if auth.uid() is null or not (
    private.is_super_admin()
    or private.has_permission('compliance.manage')
  ) then
    raise exception 'Compliance management permission required' using errcode='42501';
  end if;
  if not exists(select 1 from auth.users where id=p_user_id) then
    raise exception 'User not found' using errcode='P0002';
  end if;
  if v_scope not in ('SANDBOX','ALL') then
    raise exception 'Override scope must be SANDBOX or ALL' using errcode='22023';
  end if;
  if v_reason='' then
    raise exception 'A reason is required for KYC access overrides' using errcode='22023';
  end if;
  if p_expires_at is not null and p_expires_at<=statement_timestamp() then
    raise exception 'Override expiry must be in the future' using errcode='22023';
  end if;

  insert into compliance.kyc_access_overrides(user_id,scope,enabled,reason,expires_at,created_by,updated_by)
  values(p_user_id,v_scope,coalesce(p_enabled,false),v_reason,p_expires_at,auth.uid(),auth.uid())
  on conflict(user_id) do update set
    scope=excluded.scope,
    enabled=excluded.enabled,
    reason=excluded.reason,
    expires_at=excluded.expires_at,
    updated_by=auth.uid(),
    updated_at=statement_timestamp();

  insert into audit.records(actor_user_id,actor_type,action,resource_type,resource_id,reason,metadata)
  values(
    auth.uid(),'ADMIN',
    case when p_enabled then 'KYC_ACCESS_OVERRIDE_GRANTED' else 'KYC_ACCESS_OVERRIDE_REVOKED' end,
    'USER',p_user_id::text,v_reason,
    jsonb_build_object('scope',v_scope,'enabled',coalesce(p_enabled,false),'expiresAt',p_expires_at)
  );

  return jsonb_build_object(
    'userId',p_user_id,'enabled',coalesce(p_enabled,false),'scope',v_scope,
    'reason',v_reason,'expiresAt',p_expires_at
  );
end;
$$;

grant execute on function public.admin_set_kyc_access_override(uuid,text,boolean,text,timestamptz) to authenticated;

create or replace function public.market_proposal_options()
returns jsonb
language sql
stable
security definer
set search_path=''
as $$
  select jsonb_build_object(
    'categories','["Politics","Sports","Crypto","Business","Economy","Technology","Entertainment","Science","World","Other"]'::jsonb,
    'assets',coalesce((
      select jsonb_agg(jsonb_build_object('code',a.code,'name',a.name) order by a.code)
      from public.user_accounts ua
      join public.jurisdictions j on j.country_code=ua.country_code and j.status='ACTIVE'
      join public.jurisdiction_assets ja on ja.jurisdiction_id=j.id and ja.status='ACTIVE'
      join public.assets a on a.id=ja.asset_id and a.status='ACTIVE'
      where ua.user_id=auth.uid()
    ),'[]'::jsonb)
  );
$$;

grant execute on function public.market_proposal_options() to authenticated;

-- Preserve a category explicitly chosen by the user. AI may classify only when
-- no submitted category exists. The function is patched in place so the full
-- admission implementation remains owned by its original migration.
do $block$
declare
  v_definition text;
  v_old text := $text$v_category:=upper(regexp_replace(coalesce(nullif(btrim(p_output->>'category'),''),nullif(btrim(v_proposal.normalized_payload->>'submitted_category'),''),'GENERAL'),'[^A-Za-z0-9]+','_','g'));$text$;
  v_new text := $text$v_category:=upper(regexp_replace(coalesce(nullif(btrim(v_proposal.normalized_payload->>'submitted_category'),''),nullif(btrim(p_output->>'category'),''),'GENERAL'),'[^A-Za-z0-9]+','_','g'));$text$;
begin
  select pg_get_functiondef(p.oid) into v_definition
  from pg_proc p
  join pg_namespace n on n.oid=p.pronamespace
  where n.nspname='public' and p.proname='internal_apply_market_admission_result_unchecked'
  limit 1;

  if v_definition is not null and position(v_old in v_definition)>0 then
    execute replace(v_definition,v_old,v_new);
  end if;
end
$block$;

create or replace function public.payment_quote(p_operation text,p_asset_code text,p_amount numeric)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  acct public.user_accounts;
  asset public.assets;
  op text:=upper(trim(coalesce(p_operation,'')));
  provider_id bigint;
  provider_code text;
  provider_environment text;
  access_policy jsonb;
  fee_policy jsonb;
  limit_policy jsonb;
  required_level text;
  min_amount numeric;
  max_amount numeric;
  rate_bps numeric;
  minimum_fee numeric;
  fee numeric;
  cap_key text;
begin
  acct:=private.require_active_account();
  if op not in ('DEPOSIT','WITHDRAWAL') then raise exception 'Unsupported payment operation' using errcode='22023'; end if;
  if p_amount is null or p_amount<=0 then raise exception 'Amount must be positive' using errcode='22023'; end if;

  select * into asset from public.assets where code=upper(p_asset_code) and status='ACTIVE' limit 1;
  if asset.id is null then raise exception 'Asset not available' using errcode='P0002'; end if;
  if not exists(
    select 1
    from public.jurisdictions j
    join public.jurisdiction_assets ja on ja.jurisdiction_id=j.id
    where j.country_code=acct.country_code
      and j.status='ACTIVE'
      and ja.asset_id=asset.id
      and ja.status='ACTIVE'
  ) then
    return jsonb_build_object('enabled',false,'reason','ASSET_NOT_AVAILABLE','operation',op,'assetCode',asset.code,'amount',p_amount);
  end if;

  cap_key:=case op when 'DEPOSIT' then 'deposit' else 'withdraw' end;
  if not private.capability_enabled(cap_key,acct.country_code) then
    return jsonb_build_object('enabled',false,'reason','CAPABILITY_DISABLED','operation',op,'assetCode',asset.code,'amount',p_amount);
  end if;

  access_policy:=coalesce(private.active_policy_configuration('KYC','payment_access'),'{}'::jsonb);
  fee_policy:=coalesce(private.active_policy_configuration('FEES','payment_fees'),'{}'::jsonb);
  limit_policy:=coalesce(private.active_policy_configuration('LIMITS','payment_limits'),'{}'::jsonb);
  required_level:=coalesce(access_policy->>(case op when 'DEPOSIT' then 'deposit_min_level' else 'withdrawal_min_level' end),'NONE');
  min_amount:=coalesce((limit_policy->>(case op when 'DEPOSIT' then 'deposit_min' else 'withdrawal_min' end))::numeric,0);
  max_amount:=(limit_policy->>(case op when 'DEPOSIT' then 'deposit_max' else 'withdrawal_max' end))::numeric;

  if p_amount<min_amount then
    return jsonb_build_object('enabled',false,'reason','BELOW_MINIMUM','minimum',min_amount,'operation',op,'assetCode',asset.code,'amount',p_amount);
  end if;
  if max_amount is not null and p_amount>max_amount then
    return jsonb_build_object('enabled',false,'reason','ABOVE_MAXIMUM','maximum',max_amount,'operation',op,'assetCode',asset.code,'amount',p_amount);
  end if;

  provider_id:=command.select_provider(op,acct.country_code,asset.id,p_amount);
  if provider_id is null then
    return jsonb_build_object('enabled',false,'reason','NO_PAYMENT_PROVIDER','operation',op,'assetCode',asset.code,'amount',p_amount,'requiredKycLevel',required_level);
  end if;
  select code,environment into provider_code,provider_environment from integration.providers where id=provider_id;

  if not private.kyc_access_satisfies(auth.uid(),required_level,provider_environment) then
    return jsonb_build_object('enabled',false,'reason','KYC_REQUIRED','requiredKycLevel',required_level,'operation',op,'assetCode',asset.code,'amount',p_amount);
  end if;

  rate_bps:=coalesce((fee_policy->>(case op when 'DEPOSIT' then 'deposit_rate_bps' else 'withdrawal_rate_bps' end))::numeric,0);
  minimum_fee:=coalesce((fee_policy->>(case op when 'DEPOSIT' then 'deposit_minimum_fee' else 'withdrawal_minimum_fee' end))::numeric,0);
  fee:=greatest(round((p_amount*rate_bps/10000)::numeric,18),minimum_fee);
  if fee>p_amount then raise exception 'Fee exceeds amount' using errcode='22023'; end if;

  return jsonb_build_object(
    'enabled',true,'reason',null,'operation',op,'assetCode',asset.code,'amount',p_amount,
    'feeAmount',fee,'netAmount',p_amount-fee,'providerCode',provider_code,
    'providerEnvironment',provider_environment,'requiredKycLevel',required_level
  );
end;
$$;
