-- VAD Phase 14: maker/checker provider governance and privacy-minimized operational queues.

create table if not exists integration.provider_change_requests (
  id bigint generated by default as identity primary key,
  public_id uuid not null default gen_random_uuid() unique,
  provider_id bigint not null references integration.providers(id) on delete cascade,
  requested_status text not null check (requested_status in ('ACTIVE','DISABLED','DEGRADED','UNAVAILABLE')),
  reason text not null check (char_length(reason) between 3 and 1000),
  status text not null default 'PENDING' check (status in ('PENDING','APPROVED','REJECTED','CANCELLED')),
  requested_by uuid not null references auth.users(id) on delete restrict,
  approved_by uuid references auth.users(id) on delete restrict,
  decided_at timestamptz,
  decision_reason text,
  created_at timestamptz not null default statement_timestamp(),
  check ((status='PENDING' and approved_by is null and decided_at is null) or (status<>'PENDING' and decided_at is not null)),
  check (approved_by is null or approved_by<>requested_by)
);
create index if not exists provider_change_requests_pending_idx on integration.provider_change_requests(status,created_at) where status='PENDING';
alter table integration.provider_change_requests enable row level security;

create unique index if not exists provider_change_requests_one_pending_uq
  on integration.provider_change_requests(provider_id)
  where status='PENDING';

create or replace function public.admin_request_provider_status(
  p_provider_code text,
  p_environment text,
  p_requested_status text,
  p_reason text
)
returns uuid
language plpgsql
security definer
set search_path=''
as $$
declare
  provider integration.providers;
  req_id uuid;
  target text:=upper(trim(p_requested_status));
begin
  if not private.has_permission('providers.manage') then raise exception 'Permission required' using errcode='42501'; end if;
  if target not in ('ACTIVE','DISABLED','DEGRADED','UNAVAILABLE') then raise exception 'Invalid provider status' using errcode='22023'; end if;
  if p_reason is null or char_length(trim(p_reason))<3 then raise exception 'Reason required' using errcode='22023'; end if;
  select * into provider from integration.providers where code=upper(p_provider_code) and environment=upper(p_environment);
  if provider.id is null then raise exception 'Provider not found' using errcode='P0002'; end if;
  if provider.status=target then raise exception 'Provider already has requested status' using errcode='P0001'; end if;

  insert into integration.provider_change_requests(provider_id,requested_status,reason,requested_by)
  values(provider.id,target,trim(p_reason),auth.uid())
  returning public_id into req_id;

  insert into audit.records(actor_user_id,actor_type,action,resource_type,resource_id,before_state,after_state,reason,metadata)
  values(auth.uid(),'USER','PROVIDER_STATUS_REQUESTED','PROVIDER',provider.id::text,
         jsonb_build_object('status',provider.status),jsonb_build_object('requested_status',target),trim(p_reason),
         jsonb_build_object('provider_code',provider.code,'environment',provider.environment,'change_request_id',req_id));
  return req_id;
end;
$$;
revoke all on function public.admin_request_provider_status(text,text,text,text) from public,anon;
grant execute on function public.admin_request_provider_status(text,text,text,text) to authenticated;

create or replace function public.admin_decide_provider_status_request(
  p_request_public_id uuid,
  p_decision text,
  p_decision_reason text
)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare
  req integration.provider_change_requests;
  provider integration.providers;
  decision text:=upper(trim(p_decision));
  configured boolean;
begin
  if not private.has_permission('providers.manage') then raise exception 'Permission required' using errcode='42501'; end if;
  if decision not in ('APPROVE','REJECT') then raise exception 'Decision must be APPROVE or REJECT' using errcode='22023'; end if;
  if p_decision_reason is null or char_length(trim(p_decision_reason))<3 then raise exception 'Decision reason required' using errcode='22023'; end if;

  select * into req from integration.provider_change_requests where public_id=p_request_public_id for update;
  if req.id is null then raise exception 'Change request not found' using errcode='P0002'; end if;
  if req.status<>'PENDING' then raise exception 'Change request is no longer pending' using errcode='P0001'; end if;
  if req.requested_by=auth.uid() then raise exception 'Maker cannot approve their own provider change' using errcode='42501'; end if;
  select * into provider from integration.providers where id=req.provider_id for update;

  if decision='APPROVE' then
    configured:=coalesce((provider.public_metadata->>'configured')::boolean,false);
    if req.requested_status in ('ACTIVE','DEGRADED') and not configured then
      raise exception 'Provider cannot become active until server configuration is verified' using errcode='P0001';
    end if;
    update integration.providers set status=req.requested_status where id=provider.id;
    update integration.provider_change_requests
       set status='APPROVED',approved_by=auth.uid(),decided_at=statement_timestamp(),decision_reason=trim(p_decision_reason)
     where id=req.id;
  else
    update integration.provider_change_requests
       set status='REJECTED',approved_by=auth.uid(),decided_at=statement_timestamp(),decision_reason=trim(p_decision_reason)
     where id=req.id;
  end if;

  insert into audit.records(actor_user_id,actor_type,action,resource_type,resource_id,before_state,after_state,reason,metadata)
  values(auth.uid(),'USER',case when decision='APPROVE' then 'PROVIDER_STATUS_APPROVED' else 'PROVIDER_STATUS_REJECTED' end,
         'PROVIDER',provider.id::text,jsonb_build_object('status',provider.status),
         jsonb_build_object('requested_status',req.requested_status,'decision',decision),trim(p_decision_reason),
         jsonb_build_object('provider_code',provider.code,'environment',provider.environment,'change_request_id',req.public_id,'requested_by',req.requested_by));
end;
$$;
revoke all on function public.admin_decide_provider_status_request(uuid,text,text) from public,anon;
grant execute on function public.admin_decide_provider_status_request(uuid,text,text) to authenticated;

-- Direct admin status mutation is intentionally narrowed: activation/degradation requires maker/checker above.
create or replace function public.admin_set_provider_status(p_provider_code text,p_environment text,p_status text)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare target text:=upper(trim(p_status)); provider integration.providers;
begin
  if not private.has_permission('providers.manage') then raise exception 'Permission required' using errcode='42501'; end if;
  if target not in ('DISABLED','UNAVAILABLE') then raise exception 'ACTIVE or DEGRADED status requires maker/checker approval' using errcode='P0001'; end if;
  select * into provider from integration.providers where code=upper(p_provider_code) and environment=upper(p_environment) for update;
  if provider.id is null then raise exception 'Provider not found' using errcode='P0002'; end if;
  update integration.providers set status=target where id=provider.id;
  insert into audit.records(actor_user_id,actor_type,action,resource_type,resource_id,before_state,after_state,reason,metadata)
  values(auth.uid(),'USER','PROVIDER_SAFETY_STATUS_SET','PROVIDER',provider.id::text,jsonb_build_object('status',provider.status),jsonb_build_object('status',target),'Immediate safety downgrade',jsonb_build_object('provider_code',provider.code,'environment',provider.environment));
end;
$$;
revoke all on function public.admin_set_provider_status(text,text,text) from public,anon;
grant execute on function public.admin_set_provider_status(text,text,text) to authenticated;

create or replace function public.admin_provider_change_queue()
returns table(request_public_id uuid,provider_code text,environment text,current_status text,requested_status text,reason text,requested_by uuid,created_at timestamptz)
language plpgsql
security definer
set search_path=''
as $$
begin
  if not private.has_permission('providers.manage') then raise exception 'Permission required' using errcode='42501'; end if;
  return query
  select r.public_id,p.code,p.environment,p.status,r.requested_status,r.reason,r.requested_by,r.created_at
  from integration.provider_change_requests r join integration.providers p on p.id=r.provider_id
  where r.status='PENDING' order by r.created_at;
end;
$$;
revoke all on function public.admin_provider_change_queue() from public,anon;
grant execute on function public.admin_provider_change_queue() to authenticated;

create or replace function public.admin_kyc_queue(p_limit integer default 100)
returns table(case_public_id uuid,user_id uuid,country_code text,verification_level text,provider_code text,status text,created_at timestamptz,updated_at timestamptz,completed_at timestamptz)
language plpgsql
security definer
set search_path=''
as $$
begin
  if not private.has_permission('compliance.manage') and not private.has_permission('support.read') then raise exception 'Permission required' using errcode='42501'; end if;
  return query
  select k.public_id,k.user_id,k.country_code,k.verification_level,p.code,k.status,k.created_at,k.updated_at,k.completed_at
  from compliance.kyc_cases k left join integration.providers p on p.id=k.provider_id
  order by case k.status when 'IN_REVIEW' then 0 when 'PROVIDER_PENDING' then 1 when 'CREATED' then 2 else 3 end,k.updated_at desc
  limit greatest(1,least(coalesce(p_limit,100),500));
end;
$$;
revoke all on function public.admin_kyc_queue(integer) from public,anon;
grant execute on function public.admin_kyc_queue(integer) to authenticated;

create or replace function public.admin_payment_queue(p_limit integer default 100)
returns table(intent_public_id uuid,user_id uuid,asset_code text,operation text,amount numeric,fee_amount numeric,net_amount numeric,provider_code text,status text,failure_code text,created_at timestamptz,settled_at timestamptz)
language plpgsql
security definer
set search_path=''
as $$
begin
  if not private.has_permission('finance.read') and not private.has_permission('providers.manage') then raise exception 'Permission required' using errcode='42501'; end if;
  return query
  select i.public_id,i.user_id,a.code,i.operation,i.amount,i.fee_amount,i.net_amount,p.code,i.status,i.failure_code,i.created_at,i.settled_at
  from payments.intents i
  join public.assets a on a.id=i.asset_id
  left join integration.providers p on p.id=i.provider_id
  order by case i.status when 'FAILED' then 0 when 'PROVIDER_PENDING' then 1 when 'AUTHORIZED' then 2 when 'CREATED' then 3 else 4 end,i.created_at desc
  limit greatest(1,least(coalesce(p_limit,100),500));
end;
$$;
revoke all on function public.admin_payment_queue(integer) from public,anon;
grant execute on function public.admin_payment_queue(integer) to authenticated;
