-- VAD Phase 12: Didit KYC provider integration foundation.
-- External HTTP calls/webhook verification stay in a single Edge gateway; PostgreSQL owns KYC state.

create table if not exists integration.webhook_events (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references integration.providers(id) on delete restrict,
  provider_event_id text not null,
  category text not null check (category in ('KYC','PAYMENT','ORACLE','OTHER')),
  event_type text not null,
  payload_hash text not null,
  status text not null default 'RECEIVED' check (status in ('RECEIVED','PROCESSED','IGNORED','FAILED')),
  received_at timestamptz not null default statement_timestamp(),
  processed_at timestamptz,
  failure_reason text,
  unique(provider_id,provider_event_id)
);
alter table integration.webhook_events enable row level security;

insert into integration.providers(code,name,provider_type,environment,status,priority,capabilities,public_metadata,secret_reference)
select 'DIDIT','Didit','IDENTITY_VERIFICATION','PRODUCTION','ACTIVE',10,
       '["KYC_SESSION_CREATE","KYC_WEBHOOK","KYC_DECISION"]'::jsonb,
       '{"api_version":"v3","hosted_sessions":true,"configured":false}'::jsonb,
       'supabase://DIDIT_API_KEY,DIDIT_WEBHOOK_SECRET,DIDIT_WORKFLOW_ID'
where not exists(select 1 from integration.providers where code='DIDIT' and environment='PRODUCTION');

insert into integration.provider_routes(operation,country_code,asset_id,provider_id,priority,status,constraints)
select 'KYC','NG',null,p.id,10,'ACTIVE','{"verification_level":"STANDARD"}'::jsonb
from integration.providers p
where p.code='DIDIT' and p.environment='PRODUCTION'
  and not exists(select 1 from integration.provider_routes r where r.operation='KYC' and r.country_code='NG' and r.provider_id=p.id and r.asset_id is null);

create or replace function public.internal_prepare_kyc_case(p_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  acct public.user_accounts;
  provider bigint;
  provider_code text;
  case_row compliance.kyc_cases;
begin
  if auth.role() <> 'service_role' then raise exception 'Service role required' using errcode='42501'; end if;
  select * into acct from public.user_accounts where user_id=p_user_id;
  if acct.user_id is null or acct.status<>'ACTIVE' then raise exception 'Active account required' using errcode='P0001'; end if;

  provider:=command.select_provider('KYC',acct.country_code,null,null);
  if provider is null then raise exception 'No KYC provider configured' using errcode='P0001'; end if;
  select code into provider_code from integration.providers where id=provider;

  select * into case_row from compliance.kyc_cases
   where user_id=p_user_id and provider_id=provider and status in ('CREATED','PROVIDER_PENDING','IN_REVIEW')
   order by created_at desc limit 1;
  if case_row.id is null then
    insert into compliance.kyc_cases(user_id,country_code,verification_level,provider_id,status,requirements)
    values(p_user_id,acct.country_code,'STANDARD',provider,'CREATED',jsonb_build_object('provider',provider_code,'flow','HOSTED'))
    returning * into case_row;
  end if;

  return jsonb_build_object('casePublicId',case_row.public_id,'providerCode',provider_code,'countryCode',acct.country_code,'status',case_row.status,'providerReference',case_row.provider_reference);
end;
$$;
revoke all on function public.internal_prepare_kyc_case(uuid) from public,anon,authenticated;
grant execute on function public.internal_prepare_kyc_case(uuid) to service_role;

create or replace function public.internal_attach_kyc_session(
  p_user_id uuid,
  p_case_public_id uuid,
  p_provider_reference text,
  p_provider_status text
)
returns void
language plpgsql
security definer
set search_path=''
as $$
begin
  if auth.role() <> 'service_role' then raise exception 'Service role required' using errcode='42501'; end if;
  update compliance.kyc_cases
     set provider_reference=p_provider_reference,
         status=case when lower(coalesce(p_provider_status,'')) in ('approved') then 'VERIFIED'
                     when lower(coalesce(p_provider_status,'')) in ('declined') then 'REJECTED'
                     when lower(coalesce(p_provider_status,'')) in ('in review','in_review') then 'IN_REVIEW'
                     when lower(coalesce(p_provider_status,'')) in ('expired','kyc expired','kyc_expired') then 'EXPIRED'
                     when lower(coalesce(p_provider_status,'')) in ('abandoned') then 'CANCELLED'
                     else 'PROVIDER_PENDING' end,
         completed_at=case when lower(coalesce(p_provider_status,'')) in ('approved','declined','expired','kyc expired','kyc_expired','abandoned') then statement_timestamp() else null end
   where public_id=p_case_public_id and user_id=p_user_id;
  if not found then raise exception 'KYC case not found' using errcode='P0002'; end if;
end;
$$;
revoke all on function public.internal_attach_kyc_session(uuid,uuid,text,text) from public,anon,authenticated;
grant execute on function public.internal_attach_kyc_session(uuid,uuid,text,text) to service_role;

create or replace function public.internal_apply_kyc_webhook(
  p_provider_code text,
  p_provider_event_id text,
  p_provider_reference text,
  p_vendor_data text,
  p_provider_status text,
  p_event_type text,
  p_payload_hash text,
  p_safe_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  provider bigint;
  case_row compliance.kyc_cases;
  internal_status text;
  event_row bigint;
begin
  if auth.role() <> 'service_role' then raise exception 'Service role required' using errcode='42501'; end if;
  select id into provider from integration.providers where code=upper(p_provider_code) and provider_type='IDENTITY_VERIFICATION' order by case environment when 'PRODUCTION' then 0 else 1 end limit 1;
  if provider is null then raise exception 'Provider not registered' using errcode='P0002'; end if;

  insert into integration.webhook_events(provider_id,provider_event_id,category,event_type,payload_hash,status)
  values(provider,p_provider_event_id,'KYC',coalesce(p_event_type,'status.updated'),p_payload_hash,'RECEIVED')
  on conflict(provider_id,provider_event_id) do nothing returning id into event_row;
  if event_row is null then return jsonb_build_object('duplicate',true); end if;

  select * into case_row from compliance.kyc_cases where provider_id=provider and provider_reference=p_provider_reference limit 1;
  if case_row.id is null then
    update integration.webhook_events set status='IGNORED',processed_at=statement_timestamp(),failure_reason='UNKNOWN_SESSION' where id=event_row;
    return jsonb_build_object('duplicate',false,'ignored',true,'reason','UNKNOWN_SESSION');
  end if;
  if p_vendor_data is null or p_vendor_data<>case_row.user_id::text then
    update integration.webhook_events set status='FAILED',processed_at=statement_timestamp(),failure_reason='VENDOR_DATA_MISMATCH' where id=event_row;
    raise exception 'Vendor data mismatch' using errcode='22023';
  end if;

  internal_status:=case lower(coalesce(p_provider_status,''))
    when 'approved' then 'VERIFIED'
    when 'declined' then 'REJECTED'
    when 'in review' then 'IN_REVIEW'
    when 'in_review' then 'IN_REVIEW'
    when 'expired' then 'EXPIRED'
    when 'kyc expired' then 'EXPIRED'
    when 'kyc_expired' then 'EXPIRED'
    when 'abandoned' then 'CANCELLED'
    else 'PROVIDER_PENDING' end;

  update compliance.kyc_cases
     set status=internal_status,
         decision_metadata=coalesce(p_safe_metadata,'{}'::jsonb),
         completed_at=case when internal_status in ('VERIFIED','REJECTED','EXPIRED','CANCELLED') then statement_timestamp() else null end
   where id=case_row.id;
  update integration.webhook_events set status='PROCESSED',processed_at=statement_timestamp() where id=event_row;

  insert into eventing.domain_events(event_type,aggregate_type,aggregate_id,payload,idempotency_key)
  values('KYC_STATUS_UPDATED','KYC_CASE',case_row.public_id::text,
         jsonb_build_object('case_public_id',case_row.public_id,'provider','DIDIT','status',internal_status,'provider_status',p_provider_status),
         'kyc-webhook:'||provider::text||':'||p_provider_event_id)
  on conflict(idempotency_key) do nothing;

  return jsonb_build_object('duplicate',false,'ignored',false,'status',internal_status,'casePublicId',case_row.public_id);
end;
$$;
revoke all on function public.internal_apply_kyc_webhook(text,text,text,text,text,text,text,jsonb) from public,anon,authenticated;
grant execute on function public.internal_apply_kyc_webhook(text,text,text,text,text,text,text,jsonb) to service_role;

create or replace function public.my_kyc_status()
returns jsonb
language sql
security definer
set search_path=''
as $$
  select coalesce((
    select jsonb_build_object(
      'casePublicId',k.public_id,
      'verificationLevel',k.verification_level,
      'status',k.status,
      'providerCode',p.code,
      'providerConfigured',coalesce((p.public_metadata->>'configured')::boolean,false),
      'createdAt',k.created_at,
      'updatedAt',k.updated_at,
      'completedAt',k.completed_at,
      'expiresAt',k.expires_at
    )
    from compliance.kyc_cases k left join integration.providers p on p.id=k.provider_id
    where k.user_id=auth.uid()
    order by k.created_at desc limit 1
  ),jsonb_build_object('status','NOT_STARTED','providerCode','DIDIT','providerConfigured',false));
$$;
revoke all on function public.my_kyc_status() from public,anon;
grant execute on function public.my_kyc_status() to authenticated;
