-- VAD Phase 9: creator/social conviction runtime.
-- Social opinion remains separate from oracle truth and financial settlement.

create schema if not exists social;
revoke all on schema social from public,anon,authenticated;
grant usage on schema social to service_role;

create table if not exists social.posts (
  id bigint generated by default as identity primary key,
  public_id uuid not null default gen_random_uuid() unique,
  author_user_id uuid not null references auth.users(id) on delete cascade,
  post_type text not null default 'ANALYSIS' check (post_type in ('ANALYSIS','PREDICTION','COMMENTARY','SHORT_VIDEO')),
  body text not null check (char_length(body) between 1 and 5000),
  media_path text,
  canonical_event_id bigint references market.canonical_events(id) on delete set null,
  instrument_id bigint references market.instruments(id) on delete set null,
  stance_outcome_code text,
  confidence numeric(8,6) check (confidence is null or (confidence between 0 and 1)),
  status text not null default 'PUBLISHED' check (status in ('DRAFT','PUBLISHED','REMOVED')),
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  check (instrument_id is null or canonical_event_id is not null),
  check (post_type <> 'PREDICTION' or stance_outcome_code is not null)
);

create table if not exists social.comments (
  id bigint generated by default as identity primary key,
  public_id uuid not null default gen_random_uuid() unique,
  post_id bigint not null references social.posts(id) on delete cascade,
  author_user_id uuid not null references auth.users(id) on delete cascade,
  parent_comment_id bigint references social.comments(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  status text not null default 'PUBLISHED' check (status in ('PUBLISHED','REMOVED')),
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp()
);

create table if not exists social.reactions (
  post_id bigint not null references social.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reaction_type text not null default 'LIKE' check (reaction_type in ('LIKE','INSIGHTFUL')),
  created_at timestamptz not null default statement_timestamp(),
  primary key(post_id,user_id,reaction_type)
);

create table if not exists social.follows (
  follower_user_id uuid not null references auth.users(id) on delete cascade,
  followed_user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default statement_timestamp(),
  primary key(follower_user_id,followed_user_id),
  check(follower_user_id<>followed_user_id)
);

create index if not exists social_posts_published_created_idx on social.posts(status,created_at desc) where status='PUBLISHED';
create index if not exists social_posts_author_created_idx on social.posts(author_user_id,created_at desc);
create index if not exists social_posts_event_created_idx on social.posts(canonical_event_id,created_at desc) where canonical_event_id is not null;
create index if not exists social_comments_post_created_idx on social.comments(post_id,created_at);
create index if not exists social_follows_followed_idx on social.follows(followed_user_id);

alter table social.posts enable row level security;
alter table social.comments enable row level security;
alter table social.reactions enable row level security;
alter table social.follows enable row level security;

create trigger social_posts_updated_at before update on social.posts for each row execute function private.set_updated_at();
create trigger social_comments_updated_at before update on social.comments for each row execute function private.set_updated_at();

create or replace function public.create_conviction_post(
  p_body text,
  p_post_type text default 'ANALYSIS',
  p_instrument_public_id uuid default null,
  p_stance_outcome_code text default null,
  p_confidence numeric default null,
  p_media_path text default null
)
returns uuid
language plpgsql
security definer
set search_path=''
as $$
declare
  acct public.user_accounts;
  instrument market.instruments;
  event_id bigint;
  outcome_code text;
  post_id uuid;
  kind text:=upper(trim(coalesce(p_post_type,'ANALYSIS')));
begin
  acct:=private.require_active_account();
  if not private.capability_enabled('createPost',acct.country_code) then raise exception 'Posting is not currently enabled' using errcode='P0001'; end if;
  if kind not in ('ANALYSIS','PREDICTION','COMMENTARY','SHORT_VIDEO') then raise exception 'Invalid post type' using errcode='22023'; end if;
  if p_body is null or char_length(trim(p_body))<1 or char_length(p_body)>5000 then raise exception 'Post must be 1-5000 characters' using errcode='22023'; end if;
  if p_confidence is not null and (p_confidence<0 or p_confidence>1) then raise exception 'Confidence must be between 0 and 1' using errcode='22023'; end if;

  if p_instrument_public_id is not null then
    select * into instrument from market.instruments where public_id=p_instrument_public_id;
    if instrument.id is null then raise exception 'Market not found' using errcode='P0002'; end if;
    event_id:=instrument.canonical_event_id;
    if p_stance_outcome_code is not null then
      outcome_code:=upper(trim(p_stance_outcome_code));
      if not exists(select 1 from market.outcomes where instrument_id=instrument.id and code=outcome_code) then raise exception 'Stance is not a market outcome' using errcode='22023'; end if;
    end if;
  elsif p_stance_outcome_code is not null then
    raise exception 'A market is required for an outcome stance' using errcode='22023';
  end if;

  if kind='PREDICTION' and outcome_code is null then raise exception 'Prediction posts require a market outcome stance' using errcode='22023'; end if;

  insert into social.posts(author_user_id,post_type,body,media_path,canonical_event_id,instrument_id,stance_outcome_code,confidence,status)
  values(auth.uid(),kind,trim(p_body),nullif(trim(coalesce(p_media_path,'')),''),event_id,instrument.id,outcome_code,p_confidence,'PUBLISHED')
  returning public_id into post_id;

  insert into eventing.domain_events(event_type,aggregate_type,aggregate_id,payload,idempotency_key)
  values('SOCIAL_POST_PUBLISHED','SOCIAL_POST',post_id::text,jsonb_build_object('post_id',post_id,'author_user_id',auth.uid(),'post_type',kind,'instrument_public_id',p_instrument_public_id),'social-post:'||post_id::text);
  return post_id;
end;
$$;
revoke all on function public.create_conviction_post(text,text,uuid,text,numeric,text) from public,anon;
grant execute on function public.create_conviction_post(text,text,uuid,text,numeric,text) to authenticated;

create or replace function public.social_feed(p_limit integer default 30,p_offset integer default 0)
returns table(
  post_public_id uuid,
  author_user_id uuid,
  author_handle text,
  author_display_name text,
  author_avatar_path text,
  post_type text,
  body text,
  media_path text,
  stance_outcome_code text,
  confidence numeric,
  instrument_public_id uuid,
  event_public_id uuid,
  market_title text,
  asset_code text,
  yes_price numeric,
  no_price numeric,
  reaction_count bigint,
  comment_count bigint,
  viewer_liked boolean,
  viewer_follows_author boolean,
  created_at timestamptz
)
language sql
security definer
set search_path=''
as $$
  select p.public_id,p.author_user_id,pr.handle,pr.display_name,pr.avatar_path,p.post_type,p.body,p.media_path,p.stance_outcome_code,p.confidence,
    i.public_id,e.public_id,e.title,a.code,mc.yes_price,mc.no_price,
    (select count(*) from social.reactions r where r.post_id=p.id and r.reaction_type='LIKE'),
    (select count(*) from social.comments c where c.post_id=p.id and c.status='PUBLISHED'),
    exists(select 1 from social.reactions vr where vr.post_id=p.id and vr.user_id=auth.uid() and vr.reaction_type='LIKE'),
    exists(select 1 from social.follows f where f.follower_user_id=auth.uid() and f.followed_user_id=p.author_user_id),
    p.created_at
  from social.posts p
  left join public.profiles pr on pr.user_id=p.author_user_id
  left join market.instruments i on i.id=p.instrument_id
  left join market.canonical_events e on e.id=p.canonical_event_id
  left join public.assets a on a.id=i.asset_id
  left join public.market_catalog mc on mc.instrument_public_id=i.public_id
  where p.status='PUBLISHED'
  order by (case when exists(select 1 from social.follows f2 where f2.follower_user_id=auth.uid() and f2.followed_user_id=p.author_user_id) then 1 else 0 end) desc,p.created_at desc
  limit least(greatest(coalesce(p_limit,30),1),100) offset greatest(coalesce(p_offset,0),0);
$$;
revoke all on function public.social_feed(integer,integer) from public,anon;
grant execute on function public.social_feed(integer,integer) to authenticated;

create or replace function public.toggle_post_like(p_post_public_id uuid)
returns boolean
language plpgsql
security definer
set search_path=''
as $$
declare post_id bigint; liked boolean;
begin
  perform private.require_active_account();
  select id into post_id from social.posts where public_id=p_post_public_id and status='PUBLISHED';
  if post_id is null then raise exception 'Post not found' using errcode='P0002'; end if;
  delete from social.reactions where post_id=post_id and user_id=auth.uid() and reaction_type='LIKE';
  if found then return false; end if;
  insert into social.reactions(post_id,user_id,reaction_type) values(post_id,auth.uid(),'LIKE');
  return true;
end;
$$;
revoke all on function public.toggle_post_like(uuid) from public,anon;
grant execute on function public.toggle_post_like(uuid) to authenticated;

create or replace function public.add_post_comment(p_post_public_id uuid,p_body text)
returns uuid
language plpgsql
security definer
set search_path=''
as $$
declare post_id bigint; comment_id uuid;
begin
  perform private.require_active_account();
  if p_body is null or char_length(trim(p_body))<1 or char_length(p_body)>2000 then raise exception 'Comment must be 1-2000 characters' using errcode='22023'; end if;
  select id into post_id from social.posts where public_id=p_post_public_id and status='PUBLISHED';
  if post_id is null then raise exception 'Post not found' using errcode='P0002'; end if;
  insert into social.comments(post_id,author_user_id,body) values(post_id,auth.uid(),trim(p_body)) returning public_id into comment_id;
  return comment_id;
end;
$$;
revoke all on function public.add_post_comment(uuid,text) from public,anon;
grant execute on function public.add_post_comment(uuid,text) to authenticated;

create or replace function public.post_comments(p_post_public_id uuid,p_limit integer default 50)
returns table(comment_public_id uuid,author_user_id uuid,author_handle text,author_display_name text,body text,created_at timestamptz)
language sql
security definer
set search_path=''
as $$
  select c.public_id,c.author_user_id,p.handle,p.display_name,c.body,c.created_at
  from social.comments c join social.posts sp on sp.id=c.post_id left join public.profiles p on p.user_id=c.author_user_id
  where sp.public_id=p_post_public_id and c.status='PUBLISHED' order by c.created_at asc limit least(greatest(coalesce(p_limit,50),1),200);
$$;
revoke all on function public.post_comments(uuid,integer) from public,anon;
grant execute on function public.post_comments(uuid,integer) to authenticated;

create or replace function public.toggle_creator_follow(p_creator_user_id uuid)
returns boolean
language plpgsql
security definer
set search_path=''
as $$
begin
  perform private.require_active_account();
  if p_creator_user_id is null or p_creator_user_id=auth.uid() then raise exception 'Invalid creator' using errcode='22023'; end if;
  if not exists(select 1 from public.user_accounts where user_id=p_creator_user_id and status='ACTIVE') then raise exception 'Creator not found' using errcode='P0002'; end if;
  delete from social.follows where follower_user_id=auth.uid() and followed_user_id=p_creator_user_id;
  if found then return false; end if;
  insert into social.follows(follower_user_id,followed_user_id) values(auth.uid(),p_creator_user_id);
  return true;
end;
$$;
revoke all on function public.toggle_creator_follow(uuid) from public,anon;
grant execute on function public.toggle_creator_follow(uuid) to authenticated;
