-- VAD Phase 11: provider-neutral KYC and payment orchestration foundations.
-- External provider calls remain in Edge Functions; these tables/functions define authoritative internal state.

create schema if not exists compliance;
create schema if not exists payments;
revoke all on schema compliance from public,anon,authenticated;
revoke all on schema payments from public,anon,authenticated;
grant usage on schema compliance,payments to service_role;

create table if not exists integration.provider_routes (
  id bigint generated by default as identity primary key,
  operation text not null check (operation in ('KYC','DEPOSIT','WITHDRAWAL','REFUND','ORACLE_OBSERVATION')),
  country_code text not null check (country_code ~ '^[A-Z]{2}$'),
  asset_id bigint references public.assets(id) on delete cascade,
  provider_id bigint not null references integration.providers(id) on delete cascade,
  priority integer not null default 100 check (priority>=0),
  status text not null default 'ACTIVE' check (status in ('ACTIVE','DISABLED')),
  min_amount numeric(38,18),
  max_amount numeric(38,18),
  constraints jsonb not null default '{}'::jsonb check (jsonb_typeof(constraints)='object'),
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  unique(operation,country_code,asset_id,provider_id)
);
create trigger provider_routes_updated_at before update on integration.provider_routes for each row execute function private.set_updated_at();
alter table integration.provider_routes enable row level security;

create table if not exists compliance.kyc_cases (
  id bigint generated by default as identity primary key,
  public_id uuid not null default gen_random_uuid() unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  country_code text not null check (country_code ~ '^[A-Z]{2}$'),
  verification_level text not null default 'BASIC' check (verification_level in ('BASIC','STANDARD','ENHANCED')),
  provider_id bigint references integration.providers(id) on delete set null,
  provider_reference text,
  status text not null default 'CREATED' check (status in ('CREATED','PROVIDER_PENDING','IN_REVIEW','VERIFIED','REJECTED','EXPIRED','CANCELLED')),
  requirements jsonb not null default '{}'::jsonb check (jsonb_typeof(requirements)='object'),
  decision_metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(decision_metadata)='object'),
  expires_at timestamptz,
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  completed_at timestamptz
);
create index if not exists kyc_cases_user_created_idx on compliance.kyc_cases(user_id,created_at desc);
create unique index if not exists kyc_cases_provider_reference_uq on compliance.kyc_cases(provider_id,provider_reference) where provider_reference is not null;
create trigger kyc_cases_updated_at before update on compliance.kyc_cases for each row execute function private.set_updated_at();
alter table compliance.kyc_cases enable row level security;

create table if not exists payments.intents (
  id bigint generated by default as identity primary key,
  public_id uuid not null default gen_random_uuid() unique,
  user_id uuid not null references auth.users(id) on delete restrict,
  asset_id bigint not null references public.assets(id) on delete restrict,
  operation text not null check (operation in ('DEPOSIT','WITHDRAWAL','REFUND')),
  amount numeric(38,18) not null check (amount>0),
  fee_amount numeric(38,18) not null default 0 check (fee_amount>=0),
  net_amount numeric(38,18) generated always as (amount-fee_amount) stored,
  provider_id bigint references integration.providers(id) on delete set null,
  provider_reference text,
  provider_payload jsonb not null default '{}'::jsonb check (jsonb_typeof(provider_payload)='object'),
  status text not null default 'CREATED' check (status in ('CREATED','PROVIDER_PENDING','AUTHORIZED','SETTLED','FAILED','CANCELLED','REVERSED')),
  idempotency_key text not null unique,
  failure_code text,
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  settled_at timestamptz,
  check (net_amount>=0)
);
create index if not exists payment_intents_user_created_idx on payments.intents(user_id,created_at desc);
create unique index if not exists payment_intents_provider_reference_uq on payments.intents(provider_id,provider_reference) where provider_reference is not null;
create trigger payment_intents_updated_at before update on payments.intents for each row execute function private.set_updated_at();
alter table payments.intents enable row level security;

create table if not exists payments.webhook_events (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references integration.providers(id) on delete restrict,
  provider_event_id text not null,
  event_type text not null,
  payload_hash text not null,
  status text not null default 'RECEIVED' check (status in ('RECEIVED','PROCESSED','IGNORED','FAILED')),
  received_at timestamptz not null default statement_timestamp(),
  processed_at timestamptz,
  failure_reason text,
  unique(provider_id,provider_event_id)
);
alter table payments.webhook_events enable row level security;

create or replace function command.select_provider(
  p_operation text,
  p_country_code text,
  p_asset_id bigint default null,
  p_amount numeric default null
)
returns bigint
language sql
stable
security definer
set search_path=''
as $$
  select r.provider_id
  from integration.provider_routes r
  join integration.providers p on p.id=r.provider_id
  left join integration.provider_health h on h.provider_id=p.id
  where r.operation=upper(p_operation)
    and r.country_code=upper(p_country_code)
    and r.status='ACTIVE'
    and p.status in ('ACTIVE','DEGRADED')
    and (r.asset_id is null or r.asset_id=p_asset_id)
    and (r.min_amount is null or p_amount is null or p_amount>=r.min_amount)
    and (r.max_amount is null or p_amount is null or p_amount<=r.max_amount)
    and coalesce(h.status,'HEALTHY') not in ('DOWN','UNAVAILABLE')
  order by case p.status when 'ACTIVE' then 0 else 1 end,
           case coalesce(h.status,'HEALTHY') when 'HEALTHY' then 0 when 'DEGRADED' then 1 else 2 end,
           r.priority asc,p.priority asc,r.id asc
  limit 1;
$$;
revoke all on function command.select_provider(text,text,bigint,numeric) from public,anon,authenticated;
grant execute on function command.select_provider(text,text,bigint,numeric) to service_role;

create or replace function public.my_kyc_status()
returns jsonb
language sql
security definer
set search_path=''
as $$
  select coalesce((
    select jsonb_build_object(
      'casePublicId',k.public_id,
      'verificationLevel',k.verification_level,
      'status',k.status,
      'providerConfigured',k.provider_id is not null,
      'createdAt',k.created_at,
      'updatedAt',k.updated_at,
      'completedAt',k.completed_at,
      'expiresAt',k.expires_at
    )
    from compliance.kyc_cases k
    where k.user_id=auth.uid()
    order by k.created_at desc
    limit 1
  ),jsonb_build_object('status','NOT_STARTED','providerConfigured',false));
$$;
revoke all on function public.my_kyc_status() from public,anon;
grant execute on function public.my_kyc_status() to authenticated;

create or replace function public.my_payment_intents(p_limit integer default 30)
returns table(
  intent_public_id uuid,
  asset_code text,
  operation text,
  amount numeric,
  fee_amount numeric,
  net_amount numeric,
  status text,
  provider_configured boolean,
  failure_code text,
  created_at timestamptz,
  settled_at timestamptz
)
language sql
security definer
set search_path=''
as $$
  select i.public_id,a.code,i.operation,i.amount,i.fee_amount,i.net_amount,i.status,i.provider_id is not null,i.failure_code,i.created_at,i.settled_at
  from payments.intents i
  join public.assets a on a.id=i.asset_id
  where i.user_id=auth.uid()
  order by i.created_at desc
  limit greatest(1,least(coalesce(p_limit,30),100));
$$;
revoke all on function public.my_payment_intents(integer) from public,anon;
grant execute on function public.my_payment_intents(integer) to authenticated;

create or replace function public.provider_readiness()
returns jsonb
language sql
security definer
set search_path=''
as $$
  with acct as (select * from public.user_accounts where user_id=auth.uid()), ngn as (select id from public.assets where code='NGN' and status='ACTIVE' limit 1)
  select jsonb_build_object(
    'countryCode',acct.country_code,
    'kycConfigured',exists(select 1 from integration.provider_routes r join integration.providers p on p.id=r.provider_id where r.operation='KYC' and r.country_code=acct.country_code and r.status='ACTIVE' and p.status in ('ACTIVE','DEGRADED')),
    'depositConfigured',exists(select 1 from integration.provider_routes r join integration.providers p on p.id=r.provider_id,ngn where r.operation='DEPOSIT' and r.country_code=acct.country_code and (r.asset_id is null or r.asset_id=ngn.id) and r.status='ACTIVE' and p.status in ('ACTIVE','DEGRADED')),
    'withdrawalConfigured',exists(select 1 from integration.provider_routes r join integration.providers p on p.id=r.provider_id,ngn where r.operation='WITHDRAWAL' and r.country_code=acct.country_code and (r.asset_id is null or r.asset_id=ngn.id) and r.status='ACTIVE' and p.status in ('ACTIVE','DEGRADED')),
    'generatedAt',statement_timestamp()
  ) from acct;
$$;
revoke all on function public.provider_readiness() from public,anon;
grant execute on function public.provider_readiness() to authenticated;
