create or replace function public.admin_growth_workspace()
returns jsonb language plpgsql security definer set search_path='' as $$
begin
 if auth.uid() is null or not (private.is_super_admin() or private.has_permission('growth.read')) then raise exception 'Growth access required' using errcode='42501'; end if;
 return jsonb_build_object(
 'summary',jsonb_build_object('activeCampaigns',(select count(*) from growth.campaigns where status='ACTIVE'),'partners',(select count(*) from growth.partners where status in('ACTIVE','PAUSED')),'attributedUsers',(select count(*) from growth.attributions),'pendingRewards',(select count(*) from growth.reward_entitlements where status in('PENDING','QUALIFYING','EARNED','HELD')),'approvedLiability',(select coalesce(sum(amount),0) from growth.reward_entitlements where status in('APPROVED','PAYABLE')),'paidRewards',(select coalesce(sum(amount),0) from growth.reward_entitlements where status='PAID')),
 'campaigns',coalesce((select jsonb_agg(jsonb_build_object('publicId',c.public_id,'code',c.code,'type',c.campaign_type,'name',c.name,'description',c.short_description,'status',c.status,'rewardAssetCode',a.code,'rewardMode',c.reward_mode,'allocatedBudget',c.allocated_budget,'committedAmount',b.committed_amount,'paidAmount',b.paid_amount,'availableAmount',b.available_amount,'fundingSource',c.funding_source,'attributionModel',c.attribution_model,'attributionWindowDays',c.attribution_window_days,'rewardConfig',c.reward_config,'qualificationRule',c.qualification_rule,'eligibilityRule',c.eligibility_rule,'scoringRule',c.scoring_rule,'winnerRule',c.winner_rule,'countryCodes',c.country_codes,'perUserRewardCap',c.per_user_reward_cap,'perUserQualificationCap',c.per_user_qualification_cap,'heroImageUrl',c.hero_image_url,'cardImageUrl',c.card_image_url,'squareImageUrl',c.square_image_url,'badgeText',c.badge_text,'sponsorName',c.sponsor_name,'visualConfig',c.visual_config,'termsSummary',c.terms_summary,'startsAt',c.starts_at,'endsAt',c.ends_at,'createdAt',c.created_at) order by c.created_at desc) from growth.campaigns c left join public.assets a on a.id=c.reward_asset_id left join growth.campaign_budget_state b on b.campaign_id=c.id),'[]'::jsonb),
 'partners',coalesce((select jsonb_agg(jsonb_build_object('publicId',p.public_id,'type',p.partner_type,'name',p.name,'displayName',p.display_name,'linkedUserId',p.linked_user_id,'status',p.status,'bio',p.bio,'avatarUrl',p.avatar_url,'bannerUrl',p.banner_url,'publicMetadata',p.public_metadata,'createdAt',p.created_at) order by p.created_at desc) from growth.partners p),'[]'::jsonb),
 'contracts',coalesce((select jsonb_agg(jsonb_build_object('publicId',pc.public_id,'partnerPublicId',p.public_id,'partnerName',p.display_name,'campaignPublicId',c.public_id,'campaignName',c.name,'type',pc.contract_type,'status',pc.status,'assetCode',a.code,'cpaAmount',pc.cpa_amount,'revenueShareBps',pc.revenue_share_bps,'revenueShareDays',pc.revenue_share_days,'flatFee',pc.flat_fee,'payoutCap',pc.payout_cap,'terms',pc.terms,'startsAt',pc.starts_at,'endsAt',pc.ends_at) order by pc.created_at desc) from growth.partner_contracts pc join growth.partners p on p.id=pc.partner_id left join growth.campaigns c on c.id=pc.campaign_id left join public.assets a on a.id=pc.reward_asset_id),'[]'::jsonb),
 'links',coalesce((select jsonb_agg(jsonb_build_object('publicId',l.public_id,'code',l.code,'kind',l.link_kind,'partnerPublicId',p.public_id,'partnerName',p.display_name,'campaignPublicId',c.public_id,'campaignName',c.name,'rewardable',l.rewardable,'status',l.status,'destinationPath',l.destination_path,'expiresAt',l.expires_at) order by l.created_at desc) from growth.links l left join growth.partners p on p.id=l.partner_id left join growth.campaigns c on c.id=l.campaign_id where l.link_kind<>'INVITE'),'[]'::jsonb),
 'rewardQueue',coalesce((select jsonb_agg(jsonb_build_object('publicId',r.public_id,'campaignPublicId',c.public_id,'campaignName',c.name,'kind',r.reward_kind,'beneficiaryUserId',r.beneficiary_user_id,'beneficiaryPartnerPublicId',p.public_id,'beneficiaryPartnerName',p.display_name,'assetCode',a.code,'amount',r.amount,'status',r.status,'holdUntil',r.hold_until,'createdAt',r.created_at) order by r.created_at desc) from growth.reward_entitlements r join growth.campaigns c on c.id=r.campaign_id join public.assets a on a.id=r.asset_id left join growth.partners p on p.id=r.beneficiary_partner_id where r.status not in('PAID','REVERSED','DISQUALIFIED') limit 100),'[]'::jsonb));
end;$$;
grant execute on function public.admin_growth_workspace() to authenticated;

create or replace function public.admin_upsert_growth_campaign(p_public_id uuid,p_payload jsonb)
returns uuid language plpgsql security definer set search_path='' as $$
declare v_id bigint;v_public uuid;v_before jsonb;v_asset_id bigint;v_code text:=upper(btrim(coalesce(p_payload->>'code','')));v_type text:=upper(btrim(coalesce(p_payload->>'campaignType','')));v_mode text:=upper(btrim(coalesce(p_payload->>'rewardMode','NONE')));v_status text:=upper(btrim(coalesce(p_payload->>'status','DRAFT')));
begin
 if auth.uid() is null or not (private.is_super_admin() or private.has_permission('growth.manage')) then raise exception 'Growth management permission required' using errcode='42501'; end if;
 if v_code !~ '^[A-Z][A-Z0-9_]{2,39}$' then raise exception 'Campaign code must use letters, numbers or underscores' using errcode='22023'; end if;
 if v_type not in('REFERRAL','AFFILIATE','CHALLENGE','SPONSORED','CREATOR','SEASONAL','LAUNCH','EDUCATION') then raise exception 'Choose a valid campaign type' using errcode='22023'; end if;
 if v_mode not in('NONE','FIXED_CPA','REVENUE_SHARE','HYBRID','PRIZE_POOL','PROMOTIONAL_CREDIT','FEE_CREDIT') then raise exception 'Choose a valid reward model' using errcode='22023'; end if;
 if v_status not in('DRAFT','SCHEDULED','PAUSED') then raise exception 'Use campaign controls to activate, end or settle a campaign' using errcode='22023'; end if;
 if char_length(btrim(coalesce(p_payload->>'name','')))<3 or char_length(btrim(coalesce(p_payload->>'shortDescription','')))<3 then raise exception 'Campaign name and description are required' using errcode='22023'; end if;
 if nullif(upper(btrim(coalesce(p_payload->>'rewardAssetCode',''))),'') is not null then select id into v_asset_id from public.assets where code=upper(btrim(p_payload->>'rewardAssetCode')) and status='ACTIVE'; end if;
 if v_mode<>'NONE' and v_asset_id is null then raise exception 'Choose an active reward asset' using errcode='22023'; end if;
 if p_public_id is null then
  insert into growth.campaigns(code,campaign_type,name,short_description,full_description,status,reward_asset_id,reward_mode,allocated_budget,funding_source,attribution_model,attribution_window_days,reward_config,qualification_rule,eligibility_rule,scoring_rule,winner_rule,country_codes,per_user_reward_cap,per_user_qualification_cap,hero_image_url,card_image_url,square_image_url,badge_text,sponsor_name,visual_config,terms_summary,starts_at,ends_at,created_by,updated_by)
  values(v_code,v_type,btrim(p_payload->>'name'),btrim(p_payload->>'shortDescription'),nullif(btrim(coalesce(p_payload->>'fullDescription','')),''),v_status,v_asset_id,v_mode,coalesce((p_payload->>'allocatedBudget')::numeric,0),coalesce(nullif(upper(btrim(p_payload->>'fundingSource')),''),'VAD_MARKETING'),coalesce(nullif(upper(btrim(p_payload->>'attributionModel')),''),'LAST_TOUCH_BEFORE_SIGNUP'),coalesce((p_payload->>'attributionWindowDays')::int,30),coalesce(p_payload->'rewardConfig','{}'::jsonb),coalesce(p_payload->'qualificationRule','{}'::jsonb),coalesce(p_payload->'eligibilityRule','{}'::jsonb),coalesce(p_payload->'scoringRule','{}'::jsonb),coalesce(p_payload->'winnerRule','{}'::jsonb),coalesce(array(select jsonb_array_elements_text(coalesce(p_payload->'countryCodes','["NG"]'::jsonb))),array['NG']::text[]),nullif(p_payload->>'perUserRewardCap','')::numeric,nullif(p_payload->>'perUserQualificationCap','')::int,nullif(btrim(coalesce(p_payload->>'heroImageUrl','')),''),nullif(btrim(coalesce(p_payload->>'cardImageUrl','')),''),nullif(btrim(coalesce(p_payload->>'squareImageUrl','')),''),nullif(btrim(coalesce(p_payload->>'badgeText','')),''),nullif(btrim(coalesce(p_payload->>'sponsorName','')),''),coalesce(p_payload->'visualConfig','{}'::jsonb),nullif(btrim(coalesce(p_payload->>'termsSummary','')),''),nullif(p_payload->>'startsAt','')::timestamptz,nullif(p_payload->>'endsAt','')::timestamptz,auth.uid(),auth.uid()) returning id,public_id into v_id,v_public;
 else
  select id,to_jsonb(c) into v_id,v_before from growth.campaigns c where public_id=p_public_id for update;
  if v_id is null then raise exception 'Campaign not found' using errcode='P0002'; end if;
  update growth.campaigns set code=v_code,campaign_type=v_type,name=btrim(p_payload->>'name'),short_description=btrim(p_payload->>'shortDescription'),full_description=nullif(btrim(coalesce(p_payload->>'fullDescription','')),''),status=v_status,reward_asset_id=v_asset_id,reward_mode=v_mode,allocated_budget=coalesce((p_payload->>'allocatedBudget')::numeric,0),funding_source=coalesce(nullif(upper(btrim(p_payload->>'fundingSource')),''),'VAD_MARKETING'),attribution_model=coalesce(nullif(upper(btrim(p_payload->>'attributionModel')),''),'LAST_TOUCH_BEFORE_SIGNUP'),attribution_window_days=coalesce((p_payload->>'attributionWindowDays')::int,30),reward_config=coalesce(p_payload->'rewardConfig','{}'::jsonb),qualification_rule=coalesce(p_payload->'qualificationRule','{}'::jsonb),eligibility_rule=coalesce(p_payload->'eligibilityRule','{}'::jsonb),scoring_rule=coalesce(p_payload->'scoringRule','{}'::jsonb),winner_rule=coalesce(p_payload->'winnerRule','{}'::jsonb),country_codes=coalesce(array(select jsonb_array_elements_text(coalesce(p_payload->'countryCodes','["NG"]'::jsonb))),array['NG']::text[]),per_user_reward_cap=nullif(p_payload->>'perUserRewardCap','')::numeric,per_user_qualification_cap=nullif(p_payload->>'perUserQualificationCap','')::int,hero_image_url=nullif(btrim(coalesce(p_payload->>'heroImageUrl','')),''),card_image_url=nullif(btrim(coalesce(p_payload->>'cardImageUrl','')),''),square_image_url=nullif(btrim(coalesce(p_payload->>'squareImageUrl','')),''),badge_text=nullif(btrim(coalesce(p_payload->>'badgeText','')),''),sponsor_name=nullif(btrim(coalesce(p_payload->>'sponsorName','')),''),visual_config=coalesce(p_payload->'visualConfig','{}'::jsonb),terms_summary=nullif(btrim(coalesce(p_payload->>'termsSummary','')),''),starts_at=nullif(p_payload->>'startsAt','')::timestamptz,ends_at=nullif(p_payload->>'endsAt','')::timestamptz,updated_by=auth.uid(),updated_at=statement_timestamp() where id=v_id returning public_id into v_public;
 end if;
 insert into audit.records(actor_user_id,actor_type,action,resource_type,resource_id,before_state,after_state,reason,metadata) select auth.uid(),'ADMIN','GROWTH_CAMPAIGN_SAVED','GROWTH_CAMPAIGN',v_public::text,v_before,to_jsonb(c),'Growth campaign configuration updated',jsonb_build_object('campaignCode',c.code,'status',c.status) from growth.campaigns c where c.id=v_id;
 return v_public;
end;$$;
grant execute on function public.admin_upsert_growth_campaign(uuid,jsonb) to authenticated;

create or replace function public.admin_set_growth_campaign_status(p_campaign_public_id uuid,p_status text,p_reason text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_campaign growth.campaigns;v_target text:=upper(btrim(coalesce(p_status,'')));v_reason text:=btrim(coalesce(p_reason,''));v_before jsonb;
begin
 if auth.uid() is null or not (private.is_super_admin() or private.has_permission('growth.manage')) then raise exception 'Growth management permission required' using errcode='42501'; end if;
 if char_length(v_reason)<3 then raise exception 'Enter a reason for this campaign change' using errcode='22023'; end if;
 if v_target not in('SCHEDULED','ACTIVE','PAUSED','ENDED','CALCULATING','WINNERS_PENDING','WINNERS_APPROVED','PAYING','SETTLED','CANCELLED','ARCHIVED') then raise exception 'Invalid campaign status' using errcode='22023'; end if;
 select * into v_campaign from growth.campaigns c where c.public_id=p_campaign_public_id for update;
 if v_campaign.id is null then raise exception 'Campaign not found' using errcode='P0002'; end if;
 v_before:=to_jsonb(v_campaign);
 if v_target='ACTIVE' then
  if v_campaign.reward_mode<>'NONE' and (v_campaign.reward_asset_id is null or v_campaign.allocated_budget<=0) then raise exception 'Funded reward campaigns need a reward asset and allocated budget before activation' using errcode='22023'; end if;
  if v_campaign.ends_at is not null and v_campaign.ends_at<=statement_timestamp() then raise exception 'Campaign end time has already passed' using errcode='22023'; end if;
 end if;
 update growth.campaigns set status=v_target,approved_by=case when v_target in('SCHEDULED','ACTIVE','WINNERS_APPROVED') then coalesce(approved_by,auth.uid()) else approved_by end,activated_at=case when v_target='ACTIVE' then coalesce(activated_at,statement_timestamp()) else activated_at end,updated_by=auth.uid(),updated_at=statement_timestamp() where id=v_campaign.id;
 insert into audit.records(actor_user_id,actor_type,action,resource_type,resource_id,before_state,after_state,reason) select auth.uid(),'ADMIN','GROWTH_CAMPAIGN_STATUS_CHANGED','GROWTH_CAMPAIGN',v_campaign.public_id::text,v_before,to_jsonb(c),v_reason from growth.campaigns c where c.id=v_campaign.id;
 return jsonb_build_object('publicId',v_campaign.public_id,'status',v_target);
end;$$;
grant execute on function public.admin_set_growth_campaign_status(uuid,text,text) to authenticated;

create or replace function public.admin_upsert_growth_partner(p_public_id uuid,p_payload jsonb)
returns uuid language plpgsql security definer set search_path='' as $$
declare v_id bigint;v_public uuid;v_before jsonb;v_type text:=upper(btrim(coalesce(p_payload->>'partnerType','OTHER')));v_status text:=upper(btrim(coalesce(p_payload->>'status','DRAFT')));
begin
 if auth.uid() is null or not (private.is_super_admin() or private.has_permission('growth.manage')) then raise exception 'Growth management permission required' using errcode='42501'; end if;
 if v_type not in('CELEBRITY','INFLUENCER','CREATOR','COMMUNITY','MEDIA','AGENCY','BRAND','CAMPUS_AMBASSADOR','STRATEGIC_PARTNER','OTHER') then raise exception 'Choose a valid partner type' using errcode='22023'; end if;
 if v_status not in('DRAFT','ACTIVE','PAUSED','SUSPENDED','ENDED','ARCHIVED') then raise exception 'Invalid partner status' using errcode='22023'; end if;
 if char_length(btrim(coalesce(p_payload->>'name','')))<2 then raise exception 'Partner name is required' using errcode='22023'; end if;
 if p_public_id is null then insert into growth.partners(partner_type,name,display_name,linked_user_id,status,bio,avatar_url,banner_url,contact_metadata,public_metadata,created_by,updated_by) values(v_type,btrim(p_payload->>'name'),coalesce(nullif(btrim(p_payload->>'displayName'),''),btrim(p_payload->>'name')),nullif(p_payload->>'linkedUserId','')::uuid,v_status,nullif(btrim(coalesce(p_payload->>'bio','')),''),nullif(btrim(coalesce(p_payload->>'avatarUrl','')),''),nullif(btrim(coalesce(p_payload->>'bannerUrl','')),''),coalesce(p_payload->'contactMetadata','{}'::jsonb),coalesce(p_payload->'publicMetadata','{}'::jsonb),auth.uid(),auth.uid()) returning id,public_id into v_id,v_public;
 else select id,to_jsonb(p) into v_id,v_before from growth.partners p where p.public_id=p_public_id for update;if v_id is null then raise exception 'Partner not found' using errcode='P0002'; end if;update growth.partners set partner_type=v_type,name=btrim(p_payload->>'name'),display_name=coalesce(nullif(btrim(p_payload->>'displayName'),''),btrim(p_payload->>'name')),linked_user_id=nullif(p_payload->>'linkedUserId','')::uuid,status=v_status,bio=nullif(btrim(coalesce(p_payload->>'bio','')),''),avatar_url=nullif(btrim(coalesce(p_payload->>'avatarUrl','')),''),banner_url=nullif(btrim(coalesce(p_payload->>'bannerUrl','')),''),contact_metadata=coalesce(p_payload->'contactMetadata','{}'::jsonb),public_metadata=coalesce(p_payload->'publicMetadata','{}'::jsonb),updated_by=auth.uid(),updated_at=statement_timestamp() where id=v_id returning public_id into v_public;end if;
 insert into audit.records(actor_user_id,actor_type,action,resource_type,resource_id,before_state,after_state,reason) select auth.uid(),'ADMIN','GROWTH_PARTNER_SAVED','GROWTH_PARTNER',v_public::text,v_before,to_jsonb(p),'Growth partner configuration updated' from growth.partners p where p.id=v_id;
 return v_public;
end;$$;
grant execute on function public.admin_upsert_growth_partner(uuid,jsonb) to authenticated;

create or replace function public.admin_upsert_growth_link(p_public_id uuid,p_payload jsonb)
returns uuid language plpgsql security definer set search_path='' as $$
declare v_public uuid;v_id bigint;v_partner_id bigint;v_campaign_id bigint;v_code text:=upper(btrim(coalesce(p_payload->>'code','')));v_kind text:=upper(btrim(coalesce(p_payload->>'linkKind','AFFILIATE')));v_before jsonb;
begin
 if auth.uid() is null or not (private.is_super_admin() or private.has_permission('growth.manage')) then raise exception 'Growth management permission required' using errcode='42501'; end if;
 if v_kind not in('REFERRAL','AFFILIATE','CAMPAIGN') then raise exception 'Admin links must be referral, affiliate or campaign links' using errcode='22023'; end if;
 if v_code !~ '^[A-Z0-9][A-Z0-9_-]{2,31}$' then raise exception 'Code must be 3 to 32 letters, numbers, dashes or underscores' using errcode='22023'; end if;
 if nullif(p_payload->>'partnerPublicId','') is not null then select id into v_partner_id from growth.partners where public_id=(p_payload->>'partnerPublicId')::uuid; end if;
 if nullif(p_payload->>'campaignPublicId','') is not null then select id into v_campaign_id from growth.campaigns where public_id=(p_payload->>'campaignPublicId')::uuid; end if;
 if v_kind='AFFILIATE' and v_partner_id is null then raise exception 'Affiliate links require a partner' using errcode='22023'; end if;
 if v_kind in('REFERRAL','CAMPAIGN') and v_campaign_id is null then raise exception 'Campaign link requires a campaign' using errcode='22023'; end if;
 if p_public_id is null then insert into growth.links(code,link_kind,partner_id,campaign_id,rewardable,status,destination_path,metadata,created_by,expires_at) values(v_code,v_kind,v_partner_id,v_campaign_id,coalesce((p_payload->>'rewardable')::boolean,false),coalesce(nullif(upper(btrim(p_payload->>'status')),''),'ACTIVE'),coalesce(nullif(btrim(p_payload->>'destinationPath'),''),'/home'),coalesce(p_payload->'metadata','{}'::jsonb),auth.uid(),nullif(p_payload->>'expiresAt','')::timestamptz) returning id,public_id into v_id,v_public;
 else select id,to_jsonb(l) into v_id,v_before from growth.links l where l.public_id=p_public_id for update;if v_id is null then raise exception 'Growth link not found' using errcode='P0002'; end if;update growth.links set code=v_code,link_kind=v_kind,partner_id=v_partner_id,campaign_id=v_campaign_id,rewardable=coalesce((p_payload->>'rewardable')::boolean,false),status=coalesce(nullif(upper(btrim(p_payload->>'status')),''),'ACTIVE'),destination_path=coalesce(nullif(btrim(p_payload->>'destinationPath'),''),'/home'),metadata=coalesce(p_payload->'metadata','{}'::jsonb),expires_at=nullif(p_payload->>'expiresAt','')::timestamptz where id=v_id returning public_id into v_public;end if;
 insert into audit.records(actor_user_id,actor_type,action,resource_type,resource_id,before_state,after_state,reason) select auth.uid(),'ADMIN','GROWTH_LINK_SAVED','GROWTH_LINK',v_public::text,v_before,to_jsonb(l),'Growth tracking link updated' from growth.links l where l.id=v_id;
 return v_public;
end;$$;
grant execute on function public.admin_upsert_growth_link(uuid,jsonb) to authenticated;

create or replace function public.admin_upsert_growth_contract(p_public_id uuid,p_payload jsonb)
returns uuid language plpgsql security definer set search_path='' as $$
declare v_public uuid;v_id bigint;v_partner_id bigint;v_campaign_id bigint;v_asset_id bigint;v_before jsonb;v_type text:=upper(btrim(coalesce(p_payload->>'contractType','CPA')));
begin
 if auth.uid() is null or not (private.is_super_admin() or private.has_permission('growth.manage')) then raise exception 'Growth management permission required' using errcode='42501'; end if;
 select id into v_partner_id from growth.partners where public_id=(p_payload->>'partnerPublicId')::uuid;if v_partner_id is null then raise exception 'Partner not found' using errcode='P0002'; end if;
 if nullif(p_payload->>'campaignPublicId','') is not null then select id into v_campaign_id from growth.campaigns where public_id=(p_payload->>'campaignPublicId')::uuid; end if;
 if nullif(upper(btrim(coalesce(p_payload->>'rewardAssetCode',''))),'') is not null then select id into v_asset_id from public.assets where code=upper(btrim(p_payload->>'rewardAssetCode')) and status='ACTIVE'; end if;
 if v_type not in('CPA','REVENUE_SHARE','HYBRID','FLAT','TIERED') then raise exception 'Invalid contract type' using errcode='22023'; end if;
 if p_public_id is null then insert into growth.partner_contracts(partner_id,campaign_id,contract_type,status,reward_asset_id,cpa_amount,revenue_share_bps,revenue_share_days,flat_fee,payout_cap,terms,starts_at,ends_at,created_by) values(v_partner_id,v_campaign_id,v_type,coalesce(nullif(upper(btrim(p_payload->>'status')),''),'DRAFT'),v_asset_id,nullif(p_payload->>'cpaAmount','')::numeric,nullif(p_payload->>'revenueShareBps','')::int,nullif(p_payload->>'revenueShareDays','')::int,nullif(p_payload->>'flatFee','')::numeric,nullif(p_payload->>'payoutCap','')::numeric,coalesce(p_payload->'terms','{}'::jsonb),nullif(p_payload->>'startsAt','')::timestamptz,nullif(p_payload->>'endsAt','')::timestamptz,auth.uid()) returning id,public_id into v_id,v_public;
 else select id,to_jsonb(pc) into v_id,v_before from growth.partner_contracts pc where pc.public_id=p_public_id for update;if v_id is null then raise exception 'Partner contract not found' using errcode='P0002'; end if;update growth.partner_contracts set partner_id=v_partner_id,campaign_id=v_campaign_id,contract_type=v_type,status=coalesce(nullif(upper(btrim(p_payload->>'status')),''),'DRAFT'),reward_asset_id=v_asset_id,cpa_amount=nullif(p_payload->>'cpaAmount','')::numeric,revenue_share_bps=nullif(p_payload->>'revenueShareBps','')::int,revenue_share_days=nullif(p_payload->>'revenueShareDays','')::int,flat_fee=nullif(p_payload->>'flatFee','')::numeric,payout_cap=nullif(p_payload->>'payoutCap','')::numeric,terms=coalesce(p_payload->'terms','{}'::jsonb),starts_at=nullif(p_payload->>'startsAt','')::timestamptz,ends_at=nullif(p_payload->>'endsAt','')::timestamptz,updated_at=statement_timestamp() where id=v_id returning public_id into v_public;end if;
 insert into audit.records(actor_user_id,actor_type,action,resource_type,resource_id,before_state,after_state,reason) select auth.uid(),'ADMIN','GROWTH_CONTRACT_SAVED','GROWTH_PARTNER_CONTRACT',v_public::text,v_before,to_jsonb(pc),'Growth partner contract updated' from growth.partner_contracts pc where pc.id=v_id;
 return v_public;
end;$$;
grant execute on function public.admin_upsert_growth_contract(uuid,jsonb) to authenticated;

create or replace function public.admin_decide_growth_reward(p_reward_public_id uuid,p_decision text,p_reason text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_reward growth.reward_entitlements;v_decision text:=upper(btrim(coalesce(p_decision,'')));v_reason text:=btrim(coalesce(p_reason,''));v_before jsonb;
begin
 if auth.uid() is null or not (private.is_super_admin() or private.has_permission('growth.review')) then raise exception 'Growth review permission required' using errcode='42501'; end if;
 if v_decision not in('APPROVE','HOLD','DISQUALIFY') then raise exception 'Choose approve, hold or disqualify' using errcode='22023'; end if;
 if char_length(v_reason)<3 then raise exception 'Enter a review reason' using errcode='22023'; end if;
 select * into v_reward from growth.reward_entitlements r where r.public_id=p_reward_public_id for update;if v_reward.id is null then raise exception 'Reward not found' using errcode='P0002'; end if;v_before:=to_jsonb(v_reward);
 if v_reward.status in('PAID','REVERSED','DISQUALIFIED') then raise exception 'This reward can no longer be reviewed' using errcode='22023'; end if;
 update growth.reward_entitlements set status=case v_decision when 'APPROVE' then 'APPROVED' when 'HOLD' then 'HELD' else 'DISQUALIFIED' end,approved_by=case when v_decision='APPROVE' then auth.uid() else approved_by end,approved_at=case when v_decision='APPROVE' then statement_timestamp() else approved_at end,metadata=metadata||jsonb_build_object('reviewReason',v_reason,'reviewedBy',auth.uid(),'reviewedAt',statement_timestamp()),updated_at=statement_timestamp() where id=v_reward.id;
 insert into audit.records(actor_user_id,actor_type,action,resource_type,resource_id,before_state,after_state,reason) select auth.uid(),'ADMIN','GROWTH_REWARD_'||v_decision,'GROWTH_REWARD',v_reward.public_id::text,v_before,to_jsonb(r),v_reason from growth.reward_entitlements r where r.id=v_reward.id;
 return jsonb_build_object('publicId',v_reward.public_id,'status',case v_decision when 'APPROVE' then 'APPROVED' when 'HOLD' then 'HELD' else 'DISQUALIFIED' end);
end;$$;
grant execute on function public.admin_decide_growth_reward(uuid,text,text) to authenticated;
